### ISSUE TITLE
Support an application path prefix

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#100]
To not require a dedicated domain (or subdomain) the application can be extended to support an application path prefix.

For instance ```domain.com/{pathPrefix}/```

The biggest hurdle to support this is that the **Rollup HTML bundle plugin** currently in use supports an onlinePath however that affects the path urls of the static assets, may need to tweak those or submit PR for said plugin to better support the current design.

**Comment by StevenWeathers** [comment]
One idea would be to abandon using an HTML bundle plugin and have rollup output a json manifest of the bundled assets.
Then the go handler could build the HTML template and have greater control.

**Comment by eivindt** [comment]
I have a working(?) implementation of this (I think maybe I didn't push that branch).
It uses a config option for adding a prefix to every internal url created by the svelte components.
I _did_ have problems with the rollup for this, as the html bundle plugin didn't behave as documented (as far as I could tell), so I had to patch it to create a working build.

My version had to change both the rollup config and the thunderdome config, so it's not very elegant, so avoiding this would be nice.

**Comment by StevenWeathers** [comment]
> I have a working(?) implementation of this (I think maybe I didn't push that branch).
> It uses a config option for adding a prefix to every internal url created by the svelte components.
> I _did_ have problems with the rollup for this, as the html bundle plugin didn't behave as documented (as far as I could tell), so I had to patch it to create a working build.
> 
> My version had to change both the rollup config and the thunderdome config, so it's not very elegant, so avoiding this would be nice.

I have a local implementation as well, haven't pushed it because of the rollup workaround is not ideal. Updating the rollup config is perfectly acceptable, however like you said the behavior of the plugin for html bundle is not as ideal.  I have a few ideas I'm toying with.

**Comment by eivindt** [comment]
I've pushed what I have now, in case you want to look at it.  

Now that you've made the appRoutes structure, it would probably be better to integrate it with that, I'm just pushing what I have in case it helps.
