### ISSUE TITLE
Add Spanish (es) locale

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#104]
Looking at most common languages in Geo Location under Google Analytics Spanish is in the top 10.

**Comment by FernandoBravo66** [comment]
I can help with this issue. I can translate the resources/messages to spanish.
I would need help knowing "where" to do it

**Comment by StevenWeathers** [comment]
> I can help with this issue. I can translate the resources/messages to spanish.
> I would need help knowing "where" to do it

Sorry for just now getting around to it but I've added Spanish (es) files ready for some translations.
You can find them in the repo at ```frontend/public/lang/default/es.json``` and ```frontend/public/lang/friendly/es.json```
