### ISSUE TITLE
Add Brazilian Portuguese (pt-br) locale

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#106]
Looking at most common languages in Geo Location under Google Analytics Brazilian Portuguese (pt-br) is in the top 10.

This depends on #103

**Comment by FernandoBravo66** [comment]
I can help with this issue. I can translate the resources/messages to portuguese.
I would need help knowing "where" to do it

**Comment by StevenWeathers** [comment]
> I can help with this issue. I can translate the resources/messages to portuguese.
> I would need help knowing "where" to do it

Sorry for just now getting around to it but I've added Portuguese (pt) files ready for some translations.
You can find them in the repo at ```frontend/lang/default/pt.json``` and ```frontend/lang/friendly/pt.json```
