### ISSUE TITLE
Rename planning session for "friendly verbs"

### ISSUE THREAD

**Issue by vasileknik76** [StevenWeathers/thunderdome-planning-poker#113]
Hello I was thinked about terms naming. And I consider following:

Poker is a game.  Maybe we will replace the phrase "planning session" with a game? It seems me more friendly. 

(Optional) phrase user we can replace with player.

What do you think about it?

**Comment by StevenWeathers** [comment]
The only reason I added "friendly verbs" was for corporate use cases, however the word Game is typically blocked by corporate firewalls so that makes it not ideal.  As far as configuring it doesn't work well with translations that require context, so for now I will say we won't support this idea.

**Comment by StevenWeathers** [comment]
Actually, if they're self hosting firewall shouldn't happen.  So I think this is fair.
