### ISSUE TITLE
Link button does not lead to actual link in the story

### ISSUE THREAD

**Issue by mansweet** [StevenWeathers/thunderdome-planning-poker#123]
Seems to bring you back to the "My battles" page.  This may not be a bug, but intentional. But as a user, this is what I would have expected. 

Thanks for hosting this tool!

**Comment by StevenWeathers** [comment]
Which link button?

**Comment by mansweet** [comment]
You'll see the hyperlink is trying to send us to the link addr, but it's prepended with the thunderdome site url. 
<img width="530" alt="Screen Shot 2020-10-28 at 5 36 35 PM" src="https://user-images.githubusercontent.com/7752102/97467451-81bc3d80-1944-11eb-8b2f-bb7b32e11eb4.png">

**Comment by StevenWeathers** [comment]
Thats because you have to define a protocol for it to be an actual link e.g. http or https.
I will consider this an enhancement to validate the field value is a valid link.

**Comment by mansweet** [comment]
Thanks for clarifying! That makes sense.

**Comment by mansweet** [comment]
:muscle:
