### ISSUE TITLE
Add External API documentation

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#134]
Document which APIs are supported Externally and their inputs

**Comment by StevenWeathers** [comment]
Look at using https://apiblueprint.org/ with https://github.com/bukalapak/snowboard, possibly extracting text with https://apiblueprint.org/ or some other solution

**Comment by StevenWeathers** [comment]
Another option https://raml.org/

**Comment by whodevil** [comment]
Can you point me at where in the code the API is written so I can look at it?

**Comment by StevenWeathers** [comment]
> Can you point me at where in the code the API is written so I can look at it?

So the API routes are defined in ```routes.go``` and the handlers are in ```handlers_*.go```.
However not every route will make sense to be a public API, such as ```/api/arena/{id}``` which is for the web socket connection.

**Comment by whodevil** [comment]
We have thunderdome deployed in our lab at my work, and I want to integrate thunderdome with our story workflow :)

**Comment by whodevil** [comment]
Great tool by the way, we really like it after trying a few alternatives

**Comment by StevenWeathers** [comment]
Decided on Swagger and this will be apart of a 2.0 release with major changes to the APIs to standardize them.
