### ISSUE TITLE
Support pagination on Jira JQL search results

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#138]
Users search results for Jira JQL could be more than the maxLimit, let them paginate the results so they can navigate through a larger list.

**Comment by tnonnenm** [comment]
Currently it is possible to import Jira items multiple times. 
It might be a good idea to check if the key is already present in current battle and to mark those as imported - or maybe do an update to the existing plan on the fields (Summary, Description, ...) instead
