### ISSUE TITLE
Credentials for external STMP server in readme

### ISSUE THREAD

**Issue by codebaard** [StevenWeathers/thunderdome-planning-poker#143]
I just set up a docker instance for my team and figured that it would be helpful if the environment variables to authenticate on any arbitrary SMTP-server were mentioned in the readme.

After some digging in the code, I found them in _/pkg/email/email.go_ in the config struct and assumed they're exposed in the same way like the other variables (like _SMTP_HOST_ or _SMTP_PORT_) and in fact they are.
Could spare other users 10mins of digging this way.

Either way, keep up the good work!

**Comment by StevenWeathers** [comment]
The readme already mentions the SMTP configuration items in the configuration table, however I can see how that may go unnoticed and can split those out into their own heading.

**Comment by codebaard** [comment]
I just made sure, I didn't overlooked the variables. But _SMTP_USER_ and _SMTP_PASS_ are actually not in the readme.

**Comment by StevenWeathers** [comment]
> I just made sure, I didn't overlook the variables. But _SMTP_USER_ and _SMTP_PASS_ are actually not in the readme.

Thanks just added USER and PASS to readme, all configuration options for STMP are now in the readme.
