### ISSUE TITLE
Promote more than one person

### ISSUE THREAD

**Issue by AJOCHAM** [StevenWeathers/thunderdome-planning-poker#144]
Would be great if I could promote more than just one person to "Leader".
- In my team, we saved the URL on a WIKI page, and different team members are using this "game" for grooming. So a bigger number of "Leaders" would be awesome.

Also what if "Leader" is not available, how can I or any other become leader? 
- Maybe the 1st person can become "Leader" and then promote the right person if needed.

**Comment by StevenWeathers** [comment]
May I inquire why you have 1 session's URL on a wiki page?  The intention is every session is a new grooming session, this isolates the number of stories per session and means the sessions don't have to live long.

I'm not opposed to multiple "Leaders", there are benefits to that ability.

As far as how to become a leader, I wouldn't just make it something that happens but it could be that a "leader code" exists to take over said session if necessary.

**Comment by AJOCHAM** [comment]
> May I inquire why you have 1 session's URL on a wiki page? The intention is every session is a new grooming session, this isolates the number of stories per session and means the sessions don't have to live long.
> 
Hey 
we do reuse the same session, so we don´t need to send a new code around every time. This works for us, so each feature team can reuse the same "room"


> I'm not opposed to multiple "Leaders", there are benefits to that ability.
> 
> As far as how to become a leader, I wouldn't just make it something that happens but it could be that a "leader code" exists to take over said session if necessary.

I really like this idea, but again I would redo my "room" approach and post these 2 links for my team.

Btw I was thinking to have the option to automatically or via button pull JIRA for stories AND/OR an API to push JiraXMLs to a "room". What approach would you suggest. My idea is the "game" is always up-to-date.

**Comment by StevenWeathers** [comment]
> > May I inquire why you have 1 session's URL on a wiki page? The intention is every session is a new grooming session, this isolates the number of stories per session and means the sessions don't have to live long.
> 
> Hey
> we do reuse the same session, so we don´t need to send a new code around every time. This works for us, so each feature team can reuse the same "room"
> 
> > I'm not opposed to multiple "Leaders", there are benefits to that ability.
> > As far as how to become a leader, I wouldn't just make it something that happens but it could be that a "leader code" exists to take over said session if necessary.
> 
> I really like this idea, but again I would redo my "room" approach and post these 2 links for my team.
> 
> Btw I was thinking to have the option to automatically or via button pull JIRA for stories AND/OR an API to push JiraXMLs to a "room". What approach would you suggest. My idea is the "game" is always up-to-date.

There's been some work going on for JIRA Import from Jira API, it's not ready for release but you can clone the repo and it's in a branch.
