### ISSUE TITLE
Taking ceiling of average votes can give misleading result

### ISSUE THREAD

**Issue by zach27** [StevenWeathers/thunderdome-planning-poker#158]
It seems that taking the ceiling when averaging the voting results can give a misleading result. For example, if five users each vote a 2, but one user votes a 3, the average will be computed to a 3, which isn't as informative as rounding the average up or down (to give 2) or including one decimal place (to give 2.2). 

I realize that in some situations, taking the ceiling may make sense (e.g.  T-shirt sizing), when the team quickly needs to arrive at consensus and just take the larger value. For other contexts, taking the ceiling gives unintuitive results, and I'm wondering if rounding up or down would give a better overall result for a wider variety of situations.

**Is taking the ceiling intentional, versus rounding or including a decimal place of precision?** I would be happy to create a PR if we agree rounding or including a decimal place of precision would be more informative.

**Comment by StevenWeathers** [comment]
Points don't come in decimals so thats why the ceiling was taken.  More often than not the higher number is taken in pointing sessions to be conservative, of course its very subjective and a change could be made to option the up versus down at the battle settings level (an option on the battle creation/edit).

**Comment by zach27** [comment]
@StevenWeathers Thanks for the response. I agree adding a new user-configurable option would be best, versus changing the rounding behavior. Given that's a little more involved than what I was thinking, I won't be able to take on this work right now, but it'd be a nice feature request for the backlog.

**Comment by StevenWeathers** [comment]
> @StevenWeathers Thanks for the response. I agree adding a new user-configurable option would be best, versus changing the rounding behavior. Given that's a little more involved than what I was thinking, I won't be able to take on this work right now, but it'd be a nice feature request for the backlog.

No worries I'll add it to my list, won't take me long.
