### ISSUE TITLE
[Poker] List team battles on My Battles page

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#168]
Display a list of team battles (sorted by newest first) on My Battles page, this would allow quick access to newly created team battles.

**Comment by DanSilva41** [comment]
@StevenWeathers, can I work on this one?

**Comment by StevenWeathers** [comment]
> @StevenWeathers, can I work on this one?

Sure this one will require some SQL, Go, and frontend work to implement.

**Comment by DanSilva41** [comment]
Wonderful! I will start now

**Comment by snlucas** [comment]
Hello.
This issue has been solved?
I've been looking at Thunderdome.dev and it seems to be working.

**Comment by StevenWeathers** [comment]
I would separate them, though that could mean duplicates if they've already joined the team session.

**Comment by budokaiman** [comment]
Yes, duplicates do get shown, which can make the page a bit hefty to look at (as exampled in the first screenshot). I will push up a PR based on which screenshot you think is better UI.

**Comment by budokaiman** [comment]
I also tried side-by-side but it's a bit cramped
![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/2196125/1259aadb-f192-4c34-8c69-b9b5450dc39e)

**Comment by budokaiman** [comment]
@StevenWeathers ended up creating PR #504 with the combined view. Left reasoning on the PR

**Comment by scottux** [comment]
This is now merged. Thank you for your contribution!
