### ISSUE TITLE
Session unstable

### ISSUE THREAD

**Issue by payback-admin** [StevenWeathers/thunderdome-planning-poker#182]
We use the latest docker-version on a LINUX machine. 
We see the session is interrupted several times. How can this more stable?

This is my docker-compose.override.yml

`version: '3.1'
  services:
  thunderdome:
    environment:
      - APP_DOMAIN=machine.mydomain.com
      - CONFIG_ALLOW_JIRA_IMPORT=true
       - CONFIG_FRIENDLY_UI_VERBS=true
       - CONFIG_AVATAR_SERVICE=gravatar
       - CONFIG_SHOW_RANK=true
       - COOKIE_HASHKEY=pass12345
       - CONFIG_ALLOW_REGISTRATION=true
       - ANALYTICS_ENABLED=true
       - CONFIG_POINTS_ALLOWED=0 1/2 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 40 100 XS<5 S<13 M<20 L<40 <100 100+ ? XS S M L XL XXL
       - ANALYTICS_ID=G-X0xxxxV2W
       - COOKIE_SECURE=false
       - SMTP_HOST=webmail.mydomain.com
       - SMTP_SECURE=false
       - SMTP_SENDER=donotreply@mydomain.com
       - AUTH_METHOD=normal
       - PATH=$PATH:/go/bin
`

**Comment by StevenWeathers** [comment]
I'm unsure of what you mean by unstable and session interrupted, can you please elaborate?

**Comment by StevenWeathers** [comment]
7 days of no response, closing.
