### ISSUE TITLE
Build multi-arch docker image to support arm64

### ISSUE THREAD

**Issue by isindir** [StevenWeathers/thunderdome-planning-poker#189]
Hello,

please build multi-arch docker image, to support amd64 and arm64.

**Comment by StevenWeathers** [comment]
So the tool I use to release has a beta feature for docker manifests that would support this request.
https://goreleaser.com/customization/docker_manifest/

I will consider this option, however since the tool has this feature in beta I'm concerned it may not be ready or could be removed from the tool at any time.

**Comment by isindir** [comment]
Are you using github actions, I mean:
* https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/.github/workflows/docker.yml#L55
?

If so, the only place in this procedure where I can see `arch` being specified is here:
* https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/build/Dockerfile#L42

I think that can be removed and docker `buildx` can be used instead.

There are quite a few ready solutions to use docker buildx with github actions:
* https://github.com/marketplace/actions/docker-buildx
* https://github.com/docker/setup-buildx-action

I have not tried these personally, but `node` and `golang` base images should already have `arm64` artefacts:
* https://hub.docker.com/_/alpine?tab=tags&page=1&ordering=last_updated
* https://hub.docker.com/_/node?tab=tags&page=1&ordering=last_updated

I can try to help out, could you please point me out on where do you use `goreleaser ` ?

**Comment by StevenWeathers** [comment]
Currently I use goreleaser locally on my machine to release each version, however I'm not opposed to setting up the github action as that would make it one less thing for me to manage.

I'll look at setting this up like so
https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/

**Comment by StevenWeathers** [comment]
Ok proved this setup out in Exothermic-Story-Mapping app will apply to Thunderdome now.

https://hub.docker.com/repository/registry-1.docker.io/stevenweathers/exothermic-story-mapping/tags?page=1&ordering=last_updated

**Comment by StevenWeathers** [comment]
This is now resolved as of v1.12.9 docker image (latest).
