### ISSUE TITLE
[Poker] Add T-Shirt Sizes option to battle

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#193]
As another option to points T-Shirt sizes are commonly used in Agile, also for sizing Epics.

Options could include
XS, S, M, L, XL, XXL

**Comment by jamesbooker** [comment]
I came here to add a possible enhancement request for holding battles for things which aren't necessarily size-based. We have a process we're trialling for feedback where each user chooses one option (in this case, a colour representing a 'trait' or 'characteristic') and there's no need for averaging, etc as they are a set of unique options, rather than a numeric scale

Figured I'd add it as a comment here rather than add a new one, although I suppose the T-shirt sizes would still be 'averageable' - our use-case definitely doesn't need that

**Comment by StevenWeathers** [comment]
> I came here to add a possible enhancement request for holding battles for things which aren't necessarily size-based. We have a process we're trialling for feedback where each user chooses one option (in this case, a colour representing a 'trait' or 'characteristic') and there's no need for averaging, etc as they are a set of unique options, rather than a numeric scale
> 
> Figured I'd add it as a comment here rather than add a new one, although I suppose the T-shirt sizes would still be 'averageable' - our use-case definitely doesn't need that

Not sure I understand the exact use-case requirements, so you're saying users would "vote" on a color and you would just want to see who voted what color without the tally/averaging results displayed above the point cards?  If this is the case would a battle option to hide that feature satisfy or would it be more than that?

**Comment by jamesbooker** [comment]
Certainly we'd want tally (i.e which colour got most votes) but since they're colours (in this case, but could be used for anything - voting on a new feature for example) there's no need for averaging because averaging green/blue doesn't make sense

**Comment by jamesbooker** [comment]
I think I will add my request as a separate issue, as I hijacked the request for t-shirt sizes, but I think my request to add arbitrary voting for 'things' is probably a separate thing

**Comment by StevenWeathers** [comment]
> I think I will add my request as a separate issue, as I hijacked the request for t-shirt sizes, but I think my request to add arbitrary voting for 'things' is probably a separate thing - is that OK?

I don't think voting for "things" goes with the intended audience of this tool which is agile/scrum poker planning.  Feel free to fork the tool and make modifications to fit your use case or I would suggest building a custom tool that fits your precise needs.

**Comment by StevenWeathers** [comment]
Closing this as it doesn't seem like a feature that would see much use at this time.
