### ISSUE TITLE
Reverse proxy setup?

### ISSUE THREAD

**Issue by Minipada** [StevenWeathers/thunderdome-planning-poker#194]
I have an nginx reverse proxy setup with <URL>/scrum-poker and I can't seem to access the server.
When checking the log, I can see
```
2021/07/12 10:38:22 Access the WebUI via 127.0.0.1:8080
```
In my case, with nginx, I would need from outside 127.0.0.1.

I tried playing around with domain but it seems hardcoded [here](https://github.com/StevenWeathers/thunderdome-planning-poker/blob/c11b61c5ed5a185d6d6c57a83d13bd0b45aef644/main.go#L100)

Any idea on how to proceed?

**Comment by eivindt** [comment]
This depends on where your nginx server is located. If it's on the same computer, it should forward to 127.0.0.1, if it's not, you must make the reverse proxy forward to the ip address of the server running thunderdome.

The string in the log doesn't mean you can *only* access it via the localhost interface (127.0.0.1), you should be able to access it via any network interface.

Also, you'll have to configure the reverse proxy to strip off the path prefix before sending it to the thunderdome server, and use the pathprefix config option on the thunderdome config to add it to the html code.

**Comment by Minipada** [comment]
Okay thank you. my issue came from `http.path_prefix: /scrum-poker/`
Which I misunderstood. Now i have to deal with redirection of img and static apparently. I'll keep an update.

**Comment by eivindt** [comment]
I think I have seen a missing pathprefix handling for the avatars that may cause problems.

I never got around to making a pull request for it.

**Comment by Minipada** [comment]
So, what I needed is to have:
config.yaml: ```http.path_prefix: /scrum-poker```
nginx.conf:
```
...
  location /scrum-poker/ {
    proxy_pass http://scrum-poker:8080/scrum-poker/;
  }

```

![image](https://user-images.githubusercontent.com/1220912/125312676-c81bc600-e334-11eb-8b0c-a088a381d5d3.png)

The only part missing as you can see in the img is a redirection to the img directory. Is it a bug?

**Comment by StevenWeathers** [comment]
That's a bug, those images are missing the path prefix.  I'll get a fix in today.

**Comment by StevenWeathers** [comment]
1.13.1 fixes those 2 images.

**Comment by Minipada** [comment]
Thank you @StevenWeathers for the reactivity. I'll do a docker pull then :). i will close the issue as everything works as expected.

**Comment by Minipada** [comment]
I am getting a 404 in the avatar route as you can see. It seems different than the last issue
![image](https://user-images.githubusercontent.com/1220912/125350645-4f7e2f00-e35f-11eb-932c-1262e17ceb8a.png)

Finally, just to keep track and for future users. I needed to add those (for the websocket upgrade)
```
proxy_pass http://scrum-poker:8080/scrum-poker/;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP $remote_addr;
proxy_redirect off;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
proxy_read_timeout 86400;
```

**Comment by StevenWeathers** [comment]
Another prefix miss, I'll fix this.

**Comment by StevenWeathers** [comment]
v1.13.2 will have this fix

**Comment by Minipada** [comment]
@StevenWeathers I just wanted to point out your reactivity and support are exemplary for everyone in the open source

**Comment by StevenWeathers** [comment]
> @StevenWeathers I just wanted to point out your reactivity and support are exemplary for everyone in the open source

Thanks, I appreciate all the positive feedback this tool has gotten from the community.
