### ISSUE TITLE
Can't start battle as guest

### ISSUE THREAD

**Issue by donders** [StevenWeathers/thunderdome-planning-poker#196]
When I start a new battle from the front page, I can register as a guest and then fill out the fields to start a battle, but when I want to confirm, it takes me back to the "register as guest" page. After that, clicking the confirm button just takes me to the same page.

**Comment by StevenWeathers** [comment]
@donders Thanks for pointing this out seems I missed a scenario in testing last nights new feature.  Fix will be applied very shortly.
