### ISSUE TITLE
[E2E] Tests for Battle Page that involve File Upload

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#234]
With Cypress file uploads are another [issue](https://github.com/cypress-io/cypress/issues/170#issuecomment-340012621) so the following might or might not be achievable
- [ ]  Import Plans from Jira XML

**Comment by StevenWeathers** [comment]
Could possibly leverage https://www.npmjs.com/package/cypress-file-upload for file upload tests

**Comment by jhonatsz** [comment]
Do we still have this issue exist atm ?

**Comment by StevenWeathers** [comment]
> Do we still have this issue exist atm ?

Not sure what you mean, if you’re asking if this end to end testing issue is still open then yes it hasn’t been implemented.  This is a non user issue just end to end testing.

**Comment by jhonatsz** [comment]
@StevenWeathers  i though it was related to the issue when getting error on upload jira xml on a battle

**Comment by StevenWeathers** [comment]
@jhonatsz I found the issue, fix will be released tonight.

**Comment by jhonatsz** [comment]
awesome thanks buddy! can you link me to that issue ticket as well ? im curious what breaks it @StevenWeathers

**Comment by StevenWeathers** [comment]
> awesome thanks buddy! can you link me to that issue ticket as well ? im curious what breaks it @StevenWeathers

https://github.com/StevenWeathers/thunderdome-planning-poker/commit/ccec5704b2c83552d77879b626e86438054f0d5f

Turns out the regex was getting mangled during build time, simple fix.

**Comment by StevenWeathers** [comment]
Playwright has support for uploading files https://playwright.dev/docs/input#upload-files

**Comment by StevenWeathers** [comment]
Closing in favor of adding tests as changes are made
