### ISSUE TITLE
New font is ugly and in uppercase

### ISSUE THREAD

**Issue by InnuceEAN** [StevenWeathers/thunderdome-planning-poker#236]
Hi,

the Rajdhani font does not seem to work well with firefox 94.x (other browsers not tested, example:
![grafik](https://user-images.githubusercontent.com/50448763/145008737-5bc3f3bd-886d-451c-b8b6-33c4f8a1b470.png)

As one can see the font does not have a good appearance. Any chance that we could revert to the old font with the old styling? Or maybe make the font configurable?

**Comment by StevenWeathers** [comment]
Looks fine in latest FireFox on OSX (fresh install no custom settings).

![image](https://user-images.githubusercontent.com/846933/145040841-58e82cae-4533-47f9-a36a-0c39a8a6e340.png)

**Comment by InnuceEAN** [comment]
I'm running firefox in windows 10 in remote desktop, but I don't think that font smoothing is the problem here. It is just that the previous font had a better "readability" for me.

**Comment by StevenWeathers** [comment]
> I'm running firefox in windows 10 in remote desktop, but I don't think that font smoothing is the problem here. It is just that the previous font had a better "readability" for me.

I tested it on Firefox windows 10, the font looked fine for me.  Your screenshot shows a lack of font smoothing which I would agree is not great, however I believe that could be a symptom of either the remote desktop or the os/browser settings.  I will consider future options for fallback selection.
