### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lordlightman** [StevenWeathers/thunderdome-planning-poker#240]
Hello.

I wanted to try and deploy your project via docker-compose, grabbed the docker-compose.yml file from your repo and tweaked it a bit for my setup. After I execute 'docker-compose up' I get this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7d0729]
```

I've attached a file containing full log, docker-compose and config files.

Can you please help me understand how can I fix this issue?

[files.zip](https://github.com/StevenWeathers/thunderdome-planning-poker/files/7707824/files.zip)

**Comment by StevenWeathers** [comment]
So first glance its failing to run the database migrations, I will double check your config values but I would start looking there.

**Comment by StevenWeathers** [comment]
Not seeing anything obvious, however `aes_hashkey` belongs under config not http in your config.yaml

**Comment by StevenWeathers** [comment]
@lordlightman Alright found the issue, theres a migration that fails on a clean slate DB instance, released `v2.3.3` with the fix.  You will want to wipe your DB for it to run properly since you never had a successful run.

**Comment by lordlightman** [comment]
Thanks.

> however aes_hashkey belongs under config not http in your config.yaml

Good catch. I fixed the config file.

Unfortunately, I still get the error. I boosted the version to v2.3.3 in `docker-compose.yml` and wiped the directory with postgres data.

I've attached the new log file.

[newlog_2.3.3.log](https://github.com/StevenWeathers/thunderdome-planning-poker/files/7710376/newlog_2.3.3.log)

**Comment by StevenWeathers** [comment]
Alright I will try to run your config/compose tonight and see if I get the same error.

**Comment by StevenWeathers** [comment]
@lordlightman Found your issue, in your config you set the DB host (and mail host) as localhost, since those containers share a network (asguard) they are not in fact on your localhost.  You would have to set those to `db` and `mail` respectively as they are so named in the compose file.  You can check out the compose in the repo as an example.

**Comment by lordlightman** [comment]
@StevenWeathers, many thanks for your help. I was able to start the WebUI after network tweaks.
