### ISSUE TITLE
Enable User-Supplied Profile Pictures

### ISSUE THREAD

**Issue by krishatcher** [StevenWeathers/thunderdome-planning-poker#241]
As a user, I want to be able to change my profile picture to an image I upload so that I can be identified on the Thunderdome platform in the same graphical way as I am identified on other platforms I utilize.

**Comment by krishatcher** [comment]
One option would be to integrate an external service such as [Gravatar](https://en.gravatar.com/site/implement/) which would allow users to upload files but not force Thunderdome to store files.

**Comment by StevenWeathers** [comment]
> One option would be to integrate an external service such as [Gravatar](https://en.gravatar.com/site/implement/) which would allow users to upload files but not force Thunderdome to store files.

Great minds think alike ;)
![image](https://user-images.githubusercontent.com/846933/146283421-5307c06a-2c36-4dc6-966e-fe1e0d293619.png)
