### ISSUE TITLE
Get an error when docker run

### ISSUE THREAD

**Issue by GitHubWesley** [StevenWeathers/thunderdome-planning-poker#243]
Command: `docker run  -p 5001:8080 stevenweathers/thunderdome-planning-poker` 

Error Message:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7d0929]

goroutine 23 [running]:
github.com/golang-migrate/migrate/v4.(*Migrate).lock.func3()
        /home/runner/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.1/migrate.go:922 +0x29
created by github.com/golang-migrate/migrate/v4.(*Migrate).lock
        /home/runner/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.1/migrate.go:921 +0x1ef

**Comment by StevenWeathers** [comment]
That error occurs when Thunderdome can't connect to the postgres database, check your config values.
