### ISSUE TITLE
API method to get user's profile by api-key

### ISSUE THREAD

**Issue by tnonnenm** [StevenWeathers/thunderdome-planning-poker#252]
When using the REST API from external application several methods require the user's ID (e.g. to list user's battles, teams, ...)

Currently it is required to know the x-api-key **and** the user's ID to work with such methods.

An additional service (e.g. `GET:/api/users`) could be added that requires the x-api-key in header and returns the same response as `GET:/api/users/{userId}` for the user that owns the key.
External application could then read the id from there.

**Comment by StevenWeathers** [comment]
Great idea!
