### ISSUE TITLE
API-Doc errors

### ISSUE THREAD

**Issue by tnonnenm** [StevenWeathers/thunderdome-planning-poker#253]
Using the generated swagger JSON spec to generate a Java client following validation errors are listed:

>[WARNING] There were issues with the specification, but validation has been explicitly disabled.
>Errors:
>        -attribute paths.'/organizations/{orgId}/departments/{departmentId}/users'(post).[role].enum is unexpected
>        -attribute paths.'/teams/{teamId}/checkins'. Declared path parameter teamId needs to be defined as a path parameter in path or operation level
>        -attribute paths.'/teams/{teamId}/checkins/{checkinId}'. Declared path parameter teamId needs to be defined as a path parameter in path or operation level
>        -attribute paths.'/alerts/{alertId}'(put).[type].enum is unexpected
>        -attribute paths.'/{teamId}/users'(post).[role].enum is unexpected
>        -attribute paths.'/organizations/{orgId}/users'(post).[role].enum is unexpected
>        -attribute paths.'/teams/{teamId}/checkins/{checkinId}'. Declared path parameter checkinId needs to be defined as a path parameter in path or operation level
>        -attribute paths.'/users/{userId}/request-verify'. Declared path parameter userId needs to be defined as a path parameter in path or operation level
>        -attribute paths.'/organizations/{orgId}/departments/{departmentId}/teams/{teamId}/users'(post).[role].enum is unexpected
>        -attribute paths.'/alerts'(post).[type].enum is unexpected
>        -attribute paths.'/organizations/{orgId}/teams/{teamId}/users'(post).[role].enum is unexpected

In addition, I think there is an error in generated Swagger doc since `GET:​/users​/{userId}​/teams​/{teamId}` seems not to exist (empty response). The method that returns a user's teams seems to be `GET:​/users​/{userId}​/teams` instead.

**Comment by StevenWeathers** [comment]
So https://swagger.io/specification/v2/ supports enum based on the documentation and swaggo/swag not sure how I could help with that warning, however I am fixing the declared path issues and will look at the mentioned API endpoint.

**Comment by tnonnenm** [comment]
Enums are supported in general but the form in the JSON is not correct:

Generated:
``
                    {
                        "enum": [
                            "ERROR",
                            "INFO",
                            "NEW",
                            "SUCCESS",
                            "WARNING"
                        ],
                        "description": "Type of alert",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
``

Correct:
``
                    {
                        "description": "Type of alert",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string",
                        "enum": [
                            "ERROR",
                            "INFO",
                            "NEW",
                            "SUCCESS",
                            "WARNING"
                        ]
                        }
                    },
``

The enum must be inside "schema" and cannot be defined in the property directly. 
I found several other problems with the JSON (e.g. it is not allowed to define multiple "body" properties). Will add more details next time.

**Comment by StevenWeathers** [comment]
> Enums are supported in general but the form in the JSON is not correct:
> 
> 
> 
> Generated:
> 
> ``
> 
>                     {
> 
>                         "enum": [
> 
>                             "ERROR",
> 
>                             "INFO",
> 
>                             "NEW",
> 
>                             "SUCCESS",
> 
>                             "WARNING"
> 
>                         ],
> 
>                         "description": "Type of alert",
> 
>                         "name": "type",
> 
>                         "in": "body",
> 
>                         "required": true,
> 
>                         "schema": {
> 
>                             "type": "string"
> 
>                         }
> 
>                     },
> 
> ``
> 
> 
> 
> Correct:
> 
> ``
> 
>                     {
> 
>                         "description": "Type of alert",
> 
>                         "name": "type",
> 
>                         "in": "body",
> 
>                         "required": true,
> 
>                         "schema": {
> 
>                             "type": "string",
> 
>                         "enum": [
> 
>                             "ERROR",
> 
>                             "INFO",
> 
>                             "NEW",
> 
>                             "SUCCESS",
> 
>                             "WARNING"
> 
>                         ]
> 
>                         }
> 
>                     },
> 
> ``
> 
> 
> 
> If "in" is "body" then "schema" must be defined and "enum" must not. The definition of the enum then has to be inside "schema".
> 
> 
> 
> I found several other problems with the JSON (e.g. it is not allowed to define multiple "body" properties in one method). 
> 
> Will add more details next time.

Interesting since that would mean goswagger is not producing the correct format, will see if there's any mentioned issues there and check that I'm using the correct syntax.
