### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#256]
This project seems awesome. Seeing that it has support for LDAP is almost unbelievable. I will definitely deploy in my company soon.

Writing a Helm Chart is reasonably easy and should make it much simpler for folks to deploy in Kubernetes environments.

Just wondering if there are any plans to provide an official chart for it.

Here are some useful references:

https://github.com/helm/chart-releaser-action

If there is interest, I may be able to send a PR.

**Comment by StevenWeathers** [comment]
I'm open to a helm chart, not sure I will devote time to it anytime soon however I will be glad to accept PRs.

**Comment by StevenWeathers** [comment]
Closing, no plans to provide a helm chart at this time.
