### ISSUE TITLE
Disable orgs (and therefore departments)

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#258]
In small business, only teams are enough. It would be nice if it was possible to disable orgs (and therefore departments) through the configuration.

**Comment by StevenWeathers** [comment]
This isn't too difficult to implement, essentially just have to add config values and based on them don't expose the APIs and hide the UI elements.  I will accept PRs or when I can get around to it I will work on implementing this request.
