### ISSUE TITLE
[Auth] Infer country from LDAP

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#259]
LDAP can provide country name as well. It would be nice if this information were taken from there. Usually the attribute is `country`.

**Comment by StevenWeathers** [comment]
This is feasible, would probably be best to allow it to be configurable on the application level e.g. the attribute may be `country` or `c` depending on the LDAP setup.

**Comment by StevenWeathers** [comment]
Since #260 is resolved, this issue now also includes disabling editing of country field if LDAP provides the value

**Comment by StevenWeathers** [comment]
I'm open to a contribution for this however I don't see this as being a priority for me so closing this idea for now.
