### ISSUE TITLE
Cannot join game any longer if I click in the invite link

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#262]
It displays twice the error message: _Duplicated game session exists for your ID_

https://user-images.githubusercontent.com/29582865/150552873-5cefebac-17b5-41b4-a6b5-4370e11b8c86.mp4

**Comment by StevenWeathers** [comment]
Looking at your video you have non standard routes defined (guessing you customized the code), therefore not sure this is an actual issue with the open source build.

**Comment by felipecrs** [comment]
I didn't customize anything, I'm using your docker image as is. Why do you think that?

**Comment by StevenWeathers** [comment]
> I didn't customize anything, I'm using your docker image as is. Why do you think that?

My mistake I realized you were using friendly mode combined with a path prefix.  That said you can't open the same "game" session in the same browser this is considered a duplicate session.

**Comment by felipecrs** [comment]
Got it!
