### ISSUE TITLE
Cannot open a team anymore after creating it

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#263]
Which means I cannot start games for a Team or add more members to the team, or delete the team itself (if not by deleting the database).

https://user-images.githubusercontent.com/29582865/150553467-0467dea8-f8c1-4b2e-ada8-dee0f77aedfe.mp4

**Comment by StevenWeathers** [comment]
I believe you are using path prefix and there was an issue with path prefix for the team link you are showing here, this has since been resolved in master branch, pull latest.

**Comment by felipecrs** [comment]
Indeed, I was using path prefix. Thank you, I'll test it.
