### ISSUE TITLE
[Poker] Ordering of Jira-Export XML appears reversed in thunderdome

### ISSUE THREAD

**Issue by skekec1** [StevenWeathers/thunderdome-planning-poker#267]
We noticed that the ticket ordering of the JIRA-Export XML appears in reversed order in thunderdome. Actually we switch the ordering also during the export as an workaround to have it correctly ordered in thunderdome.

This export:

<img width="908" alt="Bildschirmfoto 2022-02-16 um 10 42 25" src="https://user-images.githubusercontent.com/41141260/154237960-7ae59e34-c925-486a-8e58-61a7b7a3ad46.png">

will result in:

<img width="1149" alt="Bildschirmfoto 2022-02-16 um 10 44 38" src="https://user-images.githubusercontent.com/41141260/154238405-17fd7def-fd40-4e20-aa6f-4181e4fb5704.png">

What are the reasons to have such handling? Is it a bug?

Best regards

Selcuk

**Comment by skekec1** [comment]
Okay, now it looks like it will be sorted by id/creation date?

**Comment by StevenWeathers** [comment]
I will have to look into this, a quick glance shows the displayed plans are sorted by created_date (ascending).

**Comment by krzwiatrzyk** [comment]
We are struggling with the same issue.

**Comment by StevenWeathers** [comment]
Hopefully this will get resolved with #434 allowing order and order could be set from the XML instead of relying on insert date.

**Comment by StevenWeathers** [comment]
434 allows ordering of stories, while this doesn't mean the import order is guaranteed it does allow the facilitator to change the ordering.
