### ISSUE TITLE
[Poker] Consider an option for a "planless" version

### ISSUE THREAD

**Issue by tym** [StevenWeathers/thunderdome-planning-poker#268]
We love this tool and how you built it. Consider adding a for "No plan" that allows users to utilize it quickly on grooming calls or standups. The ability to run it in seconds could be really useful.

**Comment by StevenWeathers** [comment]
I'll have to think through how I could add a plan less feature, however in the meantime you could just create 1 plan and keep re-activating that plan without finishing it so in essence it's a plan less session ;)

**Comment by StevenWeathers** [comment]
I don't think fundamentally aligns with the current design, therefore closing this.  To facilitate a "planless" poker session just create 1 dummy plan and reuse it for all voting purposes.
