### ISSUE TITLE
[Auth] SECURITY: Allow Specifying Self Signed CA for LDAP StartTLS Server Verification

### ISSUE THREAD

**Issue by jdsatava127** [StevenWeathers/thunderdome-planning-poker#274]
The StartTLS connection is currently executed with InsecureSkipVerify set to true in https://github.com/StevenWeathers/thunderdome-planning-poker/blob/60c5977f34e8e29c07f73755579f934bc70bb35d/api/util.go#L308. It would be great if you were able to set the InsecureSkipVerify option via the config file/env and also have the ability to specify self-signed or other CA files to use with InsecureSkipVerify set to true. This would improve the security of the LDAP connections.

**Comment by StevenWeathers** [comment]
I will consider this since, will have to look at how accepting the certificate files would work given I don't deal with LDAP on a regular basis.  I'm also happy to accept pull requests.

**Comment by StevenWeathers** [comment]
While I understand the benefit of this suggestion, I don't intend to implement this, willing to accept a PR though.
