### ISSUE TITLE
Configuration for Session ID Cookie Name

### ISSUE THREAD

**Issue by groboclown** [StevenWeathers/thunderdome-planning-poker#276]
Currently, the documentation for the configuration includes notes for the `http.backend_cookie_name` (secure cookie) and `http.frontend_cookie_name` (frontend cookie).  However, the session cookie name is `http.session_cookie_name`, which is undocumented and defaults to `sessionId`.  When using LDAP configuration, this leads to immediately returning a 401 error code after logging in if `session_cookie_name` and `backend_cookie_name` are different (it may also happen without LDAP, but I didn't try it).

As a simple work-around, I explicitly set both of these keys to the same value.  This allowed the login to work correctly.

**Comment by StevenWeathers** [comment]
Not sure how having different names for backend_cookie_name and session_cookie_name would cause issues as they are by default different names.

**Comment by groboclown** [comment]
The order of network operations that I found were:

1. User has neither frontend nor backend cookie set and accesses the login page.
2. User logs in through LDAP, which sends a request to {{/api/auth/ldap}}.  The server response sends the frontend cookie back.
3. The client sends a request to {{/api/users/(userid)/battles}} with the frontend cookie.  The server looks for the backend cookie, does not find it, and responds with a 401 error.

By setting the backend and frontend cookie to the same name, the server looks for the passed-in cookie name.

**Comment by StevenWeathers** [comment]
> The order of network operations that I found were:
> 
> 1. User has neither frontend nor backend cookie set and accesses the login page.
> 2. User logs in through LDAP, which sends a request to `/api/auth/ldap`.  The server response sends the frontend cookie back.
> 3. The client sends a request to `/api/users/(userid)/battles` with the frontend cookie.  The server looks for the backend cookie, does not find it, and responds with a 401 error.
> 
> By setting the backend and frontend cookie to the same name, the server looks for the passed-in cookie name.

Upon successful login with LDAP the backend cookie should be set, if you're not seeing it check your HTTPS cookie settings as you may not be using HTTPS and have the cookie configured for HTTPS only.  The backend and frontend cookies are not the same and should not work that way.

**Comment by groboclown** [comment]
Thanks.  That makes sense.  I'll inspect the configuration and see if this fixes it.

**Comment by StevenWeathers** [comment]
@groboclown will consider this closed for now, if you continue to see issues please elaborate.
