### ISSUE TITLE
Status code 502 when trying to update name

### ISSUE THREAD

**Issue by Maran23** [StevenWeathers/thunderdome-planning-poker#281]
When I try to update my name (https://thunderdome.dev/profile) I always get a 502 status code.
Therefore I'm unable to update it.

Request url: `https://thunderdome.dev/api/users/c019a4a9-821a-41a6-b118-7aec565b1972`
Request method: `PUT`
Request payload: `{"name":"Marius","country":"","company":"","jobTitle":"","notificationsEnabled":true,"avatar":"robohash","locale":"de"}`

---
Response:
```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.14.0 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by StevenWeathers** [comment]
I was not able to reproduce this error, what operating system and browser were you using?

**Comment by Maran23** [comment]
> I was not able to reproduce this error, what operating system and browser were you using?

I'm using Windows 10 with Google Chrome (Version 102.0.5005.63). Both are in german.
I don't have an account on https://thunderdome.dev, maybe that matters.
And I also get the same problem with Firefox and Edge.

I basically do the following steps:
1. Navigate to https://thunderdome.dev/
2. Click on 'Create battle' -> https://thunderdome.dev/register
3. Enter a name and click 'Participate' -> https://thunderdome.dev/battles
4. Then I navigate to my profile -> https://thunderdome.dev/profile
5. Change the name and click on 'Refresh profile'
6. I see a red box on the top right and a 502 as written above in the devtools

**Comment by Maran23** [comment]
Thanks! I just tried it and it works now as expected.
