### ISSUE TITLE
[Storyboard] Ability to delete comment

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#304]
Allow the author of a comment to delete a comment

**Comment by asymness** [comment]
@StevenWeathers, willing to take this up.

**Comment by StevenWeathers** [comment]
@asymness thanks for the offer, I was working on a long list of items tonight and didn't see your comment in time ;)

**Comment by asymness** [comment]
@StevenWeathers, all good. Will be looking at other open issues.
