### ISSUE TITLE
Invite link doesn't allow new guests to join a game

### ISSUE THREAD

**Issue by CSchlipp** [StevenWeathers/thunderdome-planning-poker#334]
Summary:
When inviting users to an existing game by sharing the invite link, Thunderdome redirects to the /login page and does not allow for a guest login.
If a guest session already exists in that browser, the link works as expected.

How to reproduce:
- Disable Registration, allow Guests (see environment below)
- Create a game and copy the invite link
- Open the invite link in a private browser tab

What would I expect to see:
If there is no session, allow the user to join as a guest (just like if he'd create a new game)

Workaround:
- Go to main page
- Create a new game
- Choose a guest username
- Click invite link again

Environment:
- Docker on Ubuntu
- Thunderdome 2.17.2 behind Traefik 2.7 Reverse-Proxy (No custom paths or rewrite)
- CONFIG_ALLOW_REGISTRATION: false
- CONFIG_ALLOW_JIRA_IMPORT: false
- CONFIG_DEFAULT_LOCALE: en
- CONFIG_FRIENDLY_UI_VERBS: true
- FEATURE_STORYBOARD: false
- FEATURE_RETRO: false

**Comment by StevenWeathers** [comment]
I will evaluate this use cases issue where by having registration disabled could redirect to register for guest users instead of login page.

**Comment by CSchlipp** [comment]
Can confirm that it is now working as expected.
Thanks for the quick fix!
