### ISSUE TITLE
Running in Docker

### ISSUE THREAD

**Issue by hsravat-4590** [StevenWeathers/thunderdome-planning-poker#348]
Hi, 
Is there a guide for running this in Docker

I've used the docker pull command to get the image and have tried to run it and it's producing this error:
```
{"level":"error","ts":1657292204.972851,"caller":"db/database.go:59","msg":"db driver error","version":"2.18.4","error":"dial tcp: lookup db on 192.168.65.5:53: read udp 172.17.0.3:36908->192.168.65.5:53: i/o timeout","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/db.New\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/db/database.go:59\nmain.main\n\t/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/main.go:103\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/proc.go:255"}

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7f91e9]


goroutine 53 [running]:

github.com/golang-migrate/migrate/v4.(*Migrate).lock.func3()

/home/runner/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.2/migrate.go:922 +0x29

created by github.com/golang-migrate/migrate/v4.(*Migrate).lock

/home/runner/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.2/migrate.go:921 +0x1ef
``` 

Using the `docker-compose` file has the same effect

**Comment by StevenWeathers** [comment]
That error indicates you didn't pass the DB information to the application during startup (either by environment variables or config file as documented in https://github.com/StevenWeathers/thunderdome-planning-poker/blob/master/docs/CONFIGURATION.md).

As far as the docker-compose file goes the first time you run it you may notice it'll error on timing out to the DB however it self recovers after that when the db is ready.  This never used to be a problem however docker updates seem to have made the links not as reliable.  You could run `docker-compose up db` then `docker-compose up thunderdome` when the db is fully up and running, after that initial setup the DB will be faster to load during subsequent runs.

**Comment by StevenWeathers** [comment]
Closing after no response in 15 days
