### ISSUE TITLE
[ISSUE] Unable to add user to Team/Battle/Organization if email from LDAP has uppercase letters

### ISSUE THREAD

**Issue by krzwiatrzyk** [StevenWeathers/thunderdome-planning-poker#355]
As in the title. I use LDAP authorization in Thunderdome. Adding user to Team or Battle results with following error.

By checking database I have found that my LDAP has uppercase letters in email like "Krzysztof.Wiatrzyk@email.com" and this function: 
https://github.com/StevenWeathers/thunderdome-planning-poker/blob/d60355623011b95a86bcd40d15f7bc6951765af8/api/team.go#L181 

causes issue with search in DB, because my email in DB is uppercase and search is for lowercase.

I suggest two solutions:
1) Deleting line regarding lowercasing email address.
2) Search query insensitive to letter cases:
`SELECT id FROM groups WHERE name ILIKE 'Administrator'` 
or
`SELECT subject FROM topics WHERE subject ~* 'eclipse';`

**Comment by StevenWeathers** [comment]
Guess when I implemented forced lowercase I missed the LDAP flow, I will work on a fix for this issue.
