### ISSUE TITLE
Error when authenticating with LDAP

### ISSUE THREAD

**Issue by nbazzeghin** [StevenWeathers/thunderdome-planning-poker#365]
Using version 2.24.4 and 2.25.0 we lost the ability to authenticate with LDAP. In our case we make use of Okta LDAP and 2FA. Upon entering in credentials, users get the push notification as expected from Okta and then the red toast message appear: `Error encountered attempting to authenticate warrior` 

Checking the logs yields not errors.
502 returned from `/api/auth/ldap`

Reverting to 2.24.3 resolves the issue.

**Comment by StevenWeathers** [comment]
There have been no changes to the ldap auth in those versions, however default timeouts are set perhaps the header response time from Okta is taking longer than 2 seconds.  I can make this configurable so you can increase the timeouts.

**Comment by nbazzeghin** [comment]
> 

Sounds great. Once it has been pushed, I'll give it another test and up the timeouts to confirm that is what was causing the problem.

**Comment by StevenWeathers** [comment]
@nbazzeghin please retry with https://github.com/StevenWeathers/thunderdome-planning-poker/releases/tag/v2.25.2 by configuring the timeouts to your needs, most likely the read header which is 2 seconds currently.

| Option                                | Environment Variable                | Description                                                                                                          | Default Value                          |
|---------------------------------------|-------------------------------------|----------------------------------------------------------------------------------------------------------------------|----------------------------------------|
| `http.write_tiemout`                  | HTTP_WRITE_TIMEOUT                  | HTTP response write timeout in seconds                                                                               | 5                                      |
| `http.read_tiemout`                   | HTTP_READ_TIMEOUT                   | HTTP request read timeout in seconds                                                                                 | 5                                      |
| `http.idle_tiemout`                   | HTTP_IDLE_TIMEOUT                   | HTTP request idle timeout in seconds                                                                                 | 30                                     |
| `http.read_header_tiemout`            | HTTP_READ_HEADER_TIMEOUT            | HTTP read header timeout in seconds                                                                             | 2                                      |

**Comment by StevenWeathers** [comment]
@nbazzeghin I'm closing this as the configurable options are released, if you encounter further issues please re-open or create a new ticket with further details.

**Comment by nbazzeghin** [comment]
@StevenWeathers confirming setting the `http.read_timeout` to 15 resolves the problem on v2.25.3. Thanks so much for the support!!!
