### ISSUE TITLE
[Retro] Support for Markdown export of "Done"

### ISSUE THREAD

**Issue by mihaigalos** [StevenWeathers/thunderdome-planning-poker#368]
Hi,

Fantastic work!
I noticed:
* the generated Done notes in Retros cannot be copy-pasted (bullet points not pasted).
* paragraphs (i.e.: Works, Needs Improvement, Questions) not highlighted.
* links not parsed.

Would it be possible to support i.e. Markdown here?

I would love to contribute a PR if you think this is worthwhile.

**Comment by StevenWeathers** [comment]
Not sure if markdown is the best solution here, however replacing the css style based bullet points I can being useful.
I'm open to PRs so feel free to submit one and I can provide feedback on any solutions you come up with.

**Comment by StevenWeathers** [comment]
Fixed bullet points to be non css based so they copy over correctly.  Not going to add link parsing at this time.

**Comment by mihaigalos** [comment]
Hi @StevenWeathers,

Sorry for not getting back to you on this. Life happened, baby came and had very little time.

Thanks for the implementation! 👍
