### ISSUE TITLE
[Poker] Display Description and Acceptance Criteria 

### ISSUE THREAD

**Issue by saurjk** [StevenWeathers/thunderdome-planning-poker#369]
Display the description and acceptance criteria on a sidebar or below the Story name so that it's visible as soon as a plan is activated rather than having to do it manually.

**Comment by StevenWeathers** [comment]
Feel free to submit a PR for this, if not I will get to it when I have time.

**Comment by saurjk** [comment]
I will see if i can do it and not making the site look bad :D, haven't really used go, so it will be an exercise

**Comment by StevenWeathers** [comment]
> I will see if i can do it and not making the site look bad :D, haven't really used go, so it will be an exercise

This would only be a frontend change no go should be involved as the data is already available to the frontend for this change to be made.

**Comment by saurjk** [comment]
The bigger issue is how to make it aesthetically pleasing to look at.

**Comment by StevenWeathers** [comment]
I don't see this being something easy to pull off in the UI without being too crowded, closing for now.
