### ISSUE TITLE
Add the fireworks when 100% agreement is made during the battle

### ISSUE THREAD

**Issue by gregkaczan** [StevenWeathers/thunderdome-planning-poker#373]
When all of the warriors give the same vote, we should celebrate the perfect agreement with a bang :)

For example by integrating fireworks.js and firing them in the background after the voting.

![Peek 2022-11-16 10-33](https://user-images.githubusercontent.com/1488502/202143704-6867daba-5dc4-4bd0-a952-253b8ab5e59d.gif)

**Comment by StevenWeathers** [comment]
Neat idea however I don't feel this feature would really benefit most users and adds another resource to the already decent sized javascript output.  For those reasons I will say no to this enhancement for now.
