### ISSUE TITLE
Disallow editing email when LDAP is enabled

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#374]
- This is a follow-up of #260, which disabled editing name and password when LDAP is enabled, however, I think it also makes sense to disable editing the email address.

**Comment by StevenWeathers** [comment]
> I just checked here, it seems that only administrators can edit their email (LDAP enabled). Ok, this is less of a problem, but still I think it doesn't make sense to allow anyone edit their email when LDAP is enabled, even administrators.

I can understand the risks of allowing admins to edit emails however Admins should also be knowledgable enough to know what not to do, I'll consider this as a low priority enhancement

**Comment by felipecrs** [comment]
I agree.

**Comment by StevenWeathers** [comment]
After further consideration I believe admins should have the power to edit emails, this would allow them to fix any accounts where perhaps an email changed on the ldap side and the user wants to retain their data and access on Thunderdome side.  Admin is meant to be the superadmin so they should both have power and know how to properly utilize it.

**Comment by felipecrs** [comment]
Alright. I agree too. Thank you!
