### ISSUE TITLE
[Teams] Option to display all teams not only the ones user is part of

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#375]
Let's say I'm from a team named CaptainAmerica, but I forgot to add my colleague as part of my team in Thunderdome.

Someday, this colleague have to create his own game, but since he's not part of the team (and let's say I configured Thunderdome to require a Game to be associated with a Team), he's first thought is to create a new team.

When he goes to the Teams page, he will see none there because he's not part of any, so he intuitively creates a new team named CaptainAmerica because that's the name of our team.

After all, the DB will end up with two CaptainAmerica.

If when the user clicks in the Teams tab all the teams were showed, my colleague would have noticed that the team already exists and would probably talk to me, so I could add him there.

**Comment by StevenWeathers** [comment]
I can understand this use case, I think it would have to be configurable for private instances of Thunderdome as this would not be good for the public instance experience.  I'm willing to accept a PR for this or I will get to it when I can.

**Comment by StevenWeathers** [comment]
Open to a PR, closing for now as I don't plan on implementing this myself.

**Comment by felipecrs** [comment]
Sure, thank you anyway.
