### ISSUE TITLE
Allow administrators to delete any kind of resource in the admin tab

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#376]
Currently, as an Admin I can view all teams, orgs, retros, games, etc. But I can't delete them from the UI, unless I'm part of the resource itself (like I need to be an admin of a Team to delete it, but I also have no option to become admin on a team).

Sometimes this is required to ensure the DB is clean. What I have to do is to manually run SQL calls to delete the entries I want.

**Comment by StevenWeathers** [comment]
I'll glady accept a PR for this, just haven't gotten around to adding all the CRUD features to admin panel.

**Comment by StevenWeathers** [comment]
This has been resolved.
