### ISSUE TITLE
Allow to change avatar when using gravatar, with email, but have no image from gravatar

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#377]
Currently the code disallows setting a custom avatar when using gravatar and you have an email set, but there's also the case when you don't have a image for the email. In this situation people should be able to change their avatars from the profile page as well.

https://github.com/StevenWeathers/thunderdome-planning-poker/blob/567e4713f640b8128447289b59a0310c2516f965/frontend/src/components/user/ProfileForm.svelte#L340

**Comment by StevenWeathers** [comment]
Gravatar doesn't have a lot of options for default images which is why I never implemented this, I will accept a PR for this.

**Comment by StevenWeathers** [comment]
Not going to implement this as gravatar is meant to provide the users avatar, if they haven't set it up they will get the default.
