### ISSUE TITLE
Order voting results by percentage of votes

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#38]

**Comment by TzolkinB** [comment]
New view harder to read for our case. Can we have the option of voting views? I understand why this new view could be useful.

<img width="519" alt="Screen Shot 2019-10-29 at 10 09 03 AM" src="https://user-images.githubusercontent.com/10334517/67775180-ecd2eb80-fa34-11e9-880a-2262a177d72f.png">

**Comment by StevenWeathers** [comment]
Sure I’m open to suggestions, what about the new view doesn’t work for you?

**Comment by TzolkinB** [comment]
Honestly, increasing font size would probably help a lot since we care more about how everyone votes and less about what the average is. So being able to see the info on the right side that 4 people voted for 2 and 2 people voted for 3 is what is cared about.
In my use case, we'd more likely point a story a 2 because it got the most votes  whereas the average listed is 3.

**Comment by StevenWeathers** [comment]
Awesome feedback I’ve gathered some additional ideas and will work on it. Think I’ll be going back to cards but make it clearer what the most votes are and who voted for what.

**Comment by StevenWeathers** [comment]
Brought back cards, added Average/Highest in a simpler way.
Ideally will be adding a quicker way to see who voted what soon as I can debug a potential bug with Svelte.

**Comment by TzolkinB** [comment]
Nice changes! Team was impressed. :D There does seem to be a small z-index issue when you hover over a voting number.
<img width="266" alt="Screen Shot 2019-11-06 at 10 06 35 AM" src="https://user-images.githubusercontent.com/10334517/68310173-8b86ca00-007d-11ea-80ea-ce0cfce59c33.png">

**Comment by StevenWeathers** [comment]
Good find I just noticed that yesterday and will fix it tonight thanks!
