### ISSUE TITLE
[Poker] Vote timer starting from 1hr instead of 0

### ISSUE THREAD

**Issue by Adrian-Grimm** [StevenWeathers/thunderdome-planning-poker#382]
Would be nice to have a configurable vote countdown instead of this static solution:

https://github.com/StevenWeathers/thunderdome-planning-poker/blob/567e4713f640b8128447289b59a0310c2516f965/frontend/src/pages/Battle.svelte#L56

**Comment by StevenWeathers** [comment]
Countdown is really the wrong term for what the current feature is, it counts how long the vote has been active.
Are you suggesting a configurable amount of time? e.g. 3 minutes?

**Comment by Adrian-Grimm** [comment]
@StevenWeathers  OK then I think there is also a Bug - because I get always a countdown starting with 1h. Think there could be an issue with converting server/client timezones... But it would be OK is this is only counting up from 0 instead....

**Comment by StevenWeathers** [comment]
> @StevenWeathers OK then I think there is also a Bug - because I get always a countdown starting with 1h. Think there could be an issue with converting server/client timezones... But it would be OK is this is only counting up from 0 instead....

Sounds like a timezone bug, label updated.

**Comment by StevenWeathers** [comment]
This should be resolved with the update from timestamp to timestamptz for the database columns.  Timezones should now apply for the timer.
