### ISSUE TITLE
[Battle] Add priority column

### ISSUE THREAD

**Issue by guillain** [StevenWeathers/thunderdome-planning-poker#389]
Hi,

Thanks for the job! Really helpful in my d2d :)

One thing is missing for my usage is the priority of the story.
In fact for me it's really useful when we review it to sort it and by focus first on the most important elements.

Thanks in advance, and Happy New Year!!!

**Comment by ajcool2k** [comment]
@StevenWeathers 

I really like the enhancement idea brought up by @guillain
Maybe a dumb question. After putting the priorities on all of my stories and bugs, how can I sort them out accordingly?
