### ISSUE TITLE
[Poker] Import Stories from Jira

### ISSUE THREAD

**Issue by kentmartin73** [StevenWeathers/thunderdome-planning-poker#392]
Hi,

I'd like to hit the Jira APIs and pull in plans directly.  I see support for this was done, then the branch seems to be abandoned.  Are there any plans to merge that back in?

Thanks,

Kent

**Comment by StevenWeathers** [comment]
That feature was never finished, I'm open to PRs that want to implement such a feature however it hasn't been a priority for me.

**Comment by StevenWeathers** [comment]
No plans to implement this, however open to a future PR.
