### ISSUE TITLE
Hide names from battle 

### ISSUE THREAD

**Issue by zakkatkk** [StevenWeathers/thunderdome-planning-poker#395]
I've noticed a common denominator of not meeting sprint goals is underestimation of the complexity of issues. Almost every sprint, every team, every company I’ve ever worked at struggles with under-estimating. Makes me wonder if part of the problem lies within the process. 

I wanted to propose a simple feature - A hide names for battle toggle. 

People behave differently when they know they’re being watched. There's at least some reason to speculate the perceived scrutiny and judgement of colleagues might lead some to over-simplify their estimate of a task. After all nobody _wants_ to be the odd one out who thinks a task is more difficult than everyone else, because that might mean they're not as good at their job as everyone else. Yet the point of sprint poker is to be objective and honest. 

The option to withdraw a higher estimate without justification may lead to more realistic appraisal and even make those who estimated higher more willing to justify the vote, with increased likelihood seeing support of their peers without the calculus of judging who they were.
"I see we have mostly 3's and a couple of 5's. Those who voted 5, speak now if you feel you have good reason or hold your peace."

**Comment by StevenWeathers** [comment]
I can see this being done different ways, I think the best solution would to hide the names for each voted value as well as the individuals voted values.  That way you can still see how's in the battle.
