### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mahdihmb** [StevenWeathers/thunderdome-planning-poker#400]
Hi,
Thank you for this excellent app.

Please add RTL support to app (maybe by providing DIRECTION=RTL config). There is problem in viewing persian and english text toghether in plans title/description at battles or retro cards.

**Comment by StevenWeathers** [comment]
I think this should be handled by adding Persian as a selectable language and using direction defined by language so this will work on the public instance as well as private instances of Thunderdome.  That said I'm looking into what the best solution for applying RTL is.

**Comment by StevenWeathers** [comment]
I've started a PR that will add RTL support with Persian (Farsi) as a selectable language.  Thankfully the css framework Tailwind has experimental support for RTL.

**Comment by mahdihmb** [comment]
That would be great, Thank you.
If you want, I can help with the translation.

**Comment by StevenWeathers** [comment]
> That would be great, Thank you. If you want, I can help with the translation.

Any translations are greatly appreciated.

**Comment by StevenWeathers** [comment]
@mahdihmb Initial support for Persian RTL has been merged, feel free to submit a PR for any translations you would like to contribute.  I did my best to update all styles impacting RTL, however there is bound to be some bugs so if you find some please open an issue and I will resolve or I will accept PRs with fixes to direction styles as well.
