### ISSUE TITLE
Unable to create any users

### ISSUE THREAD

**Issue by dawivid** [StevenWeathers/thunderdome-planning-poker#406]
Hi,

I am struggling to create any users. When I hit create I get this debug:

thunderdome-db-1    | 2023-03-29 12:20:27.684 UTC [33] ERROR:  null value in column "user_id" of relation "user_verify" violates not-null constraint
thunderdome-db-1    | 2023-03-29 12:20:27.684 UTC [33] DETAIL:  Failing row contains (ab18cdbb-d1d8-48bf-ab6a-516bdf4510f0, null, 2023-03-29 12:20:27.683603, 2023-03-30 12:20:27.683603).
thunderdome-db-1    | 2023-03-29 12:20:27.684 UTC [33] CONTEXT:  SQL statement "INSERT INTO user_verify (user_id) VALUES (userId) RETURNING verify_id"
thunderdome-db-1    |   PL/pgSQL function register_existing_user(uuid,character varying,character varying,text,character varying) line 14 at SQL statement
thunderdome-db-1    | 2023-03-29 12:20:27.684 UTC [33] STATEMENT:  SELECT userId, verifyId FROM register_existing_user($1, $2, $3, $4, $5);

Any ideas what I am doing wrong?

**Comment by dawivid** [comment]
my docker compose looks like this:

---

services:
  thunderdome:
    #build:
    #  context: .
    #  dockerfile: ./build/Dockerfile
    image: stevenweathers/thunderdome-planning-poker
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    environment:
      APP_DOMAIN: thunderdome.ocr.cr14.net
      COOKIE_SECURE: "false"
      SMTP_SECURE: "false"
      SMTP_HOST: mail
      DB_NAME: thunderdome
      DB_USER: thor
      DB_PASS: odinson
    volumes:
      - ./etc:/etc/thunderdome
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_DB: thunderdome
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: odinson
    ports:
      - 5432:5432
    volumes:
      - /opt/thunderdome/data:/var/lib/postgresql/data
  mail:
    image: djfarrelly/maildev:1.1.0
    restart: always
    ports:
      - 1080:80
      - 1025:25

**Comment by StevenWeathers** [comment]
It looks like you're trying to register a user from a guest user session, based on your domain are the cookies getting properly set?  To me it looks like the userId isn't making it through from the cookie to the create user flow.

**Comment by dawivid** [comment]
I have now tried it with normal authentication. The error I am getting is Error returning Teams and Battles, but without being able to login I don't see how there could be any teams or battles

**Comment by StevenWeathers** [comment]
> THanks Steven,
> 
> 
> 
> No joy yet.
> 
> 
> 
> Why are you using port 3085? 
> 
> 
> 
> Here is my config 
> 
>    location / {
> 
>      proxy_set_header X-Forwarded-Host $host;
> 
>      proxy_set_header X-Forwarded-Server $host;
> 
>      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>      proxy_pass http://thunderdome:8080;
> 
>      client_max_body_size 10M;
> 
>    }
> 
>  }

I'm using port 3085 for no specific reason, I have multiple applications running on the same server.

**Comment by dawivid** [comment]
Still nothing Steven,

What should I be looking for in terms of comms with the cookies?

**Comment by StevenWeathers** [comment]
Did you ever figure this out, I don't see any obvious reason your setup didn't work though it could be related to the cookies/proxy.

**Comment by dawivid** [comment]
I still haven't to be honest. We ended up using your hosted version. I would be keen still to get it going but I am honestly out of ideas. Not sure how to troubleshoot the cookies, if you have any ideas they would be gratefully received.

**Comment by StevenWeathers** [comment]
Closing since the problem has not been identified as originating from Thunderdome itself.
