### ISSUE TITLE
Cannot login when navigating embedded in a website

### ISSUE THREAD

**Issue by harshlarsh** [StevenWeathers/thunderdome-planning-poker#408]
Not sure if the error is in the host app or Thunderdome. I'm using https://app.gather.town/app and want to set up Thunderdome as a "game" at a table for our team to "Play" to run meetings.

I have set up a custom game object with the URL to a Battle I've already created, as well as trying the main login page. When I interact with the object (open it embedded in the app), the website loads but says it can't find the battle, or in the login page will not accept login with correct credentials or a guest. All three say they are looking for battles and users in screenshot.

![battle setup](https://user-images.githubusercontent.com/110193566/230180871-f265f6d2-8f99-42d7-945a-68b23c7e5233.png)
![game set-up](https://user-images.githubusercontent.com/110193566/230180874-269ac9c9-8867-4c5c-b844-9b525fd2dd43.png)
![url for battle direct](https://user-images.githubusercontent.com/110193566/230180876-85dfc447-ac8c-44d6-a98d-0ca205108f6e.png)

**Comment by StevenWeathers** [comment]
Thunderdome uses cookies for the session, this is not a use case that would support being embedded.
