### ISSUE TITLE
e2e testing problem

### ISSUE THREAD

**Issue by RipCodeee** [StevenWeathers/thunderdome-planning-poker#414]
hey, I'm working on your project, and I created a feature that allow to insert csv file into the battle, and I don't understand well how I can test this, can you with the tools you suggested, any help with it?

**Comment by StevenWeathers** [comment]
E2E testing is done with [Playwright](https://playwright.dev/) there are existing tests in e2e directory for you to copy from.  As far as uploading a file there are examples online of how to do so with Playwright.
