### ISSUE TITLE
Wrong Average calculation

### ISSUE THREAD

**Issue by aslafy-z** [StevenWeathers/thunderdome-planning-poker#416]
It looks like the average is wrongly calculated. I tested with all the rounding methods. With one or two persons pointing 0.5, the average is set to 1 instead of 0.5. 
 
![image](https://user-images.githubusercontent.com/8191198/236413535-4ee40091-52d3-4b1a-9f04-8d10368345eb.png)

**Comment by StevenWeathers** [comment]
This is kind of an expected outlier, all point values are whole numbers except the 1/2 and a math.ceil is being used for the average.  Logic could be added to determine if only 1/2 value was entered.

**Comment by StevenWeathers** [comment]
Added logic to not round the half point only vote result.
