### ISSUE TITLE
[Poker] Battle is stuck trying to load page when 'Join Battle' button is selected

### ISSUE THREAD

**Issue by may2024** [StevenWeathers/thunderdome-planning-poker#419]
'Calicans Refinement' Battle (with 312 of 354 plans pointed) is stuck trying to load page when 'Join Battle' button is selected.
I am not able to use this battle and noticed this started happening about 3 or more weeks ago. It actually got stuck while my team was in the middle of using it.
Since then, when I select the 'Join Battle' button, the screen will reload stating "Loading Battle Plans..." and then it is stuck there.
I created a new Battle (Calicans Refinement 1) so my team can move forward but I cannot delete this original battle since I would need to get to the next screen before I can delete it.
Request assistance to either clear up the issue for 'Calicans Refinement' battle or delete it.

Thank you for any assistance you can provide.
![Screenshot 2023-06-06 at 5 58 34 PM](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/135764103/f122bc94-1bc9-4d2a-9d74-0e6d61d3f1f9)

**Comment by StevenWeathers** [comment]
I'll take a look at this as soon as I can, likely the number of stories is too much for a single battle response would be my guess.

**Comment by may2024** [comment]
Thank you for getting back to me. 
If that is the cause, feel free to delete all previous data for that battle.

**Comment by StevenWeathers** [comment]
Turns out this was a frontend bug which I have now fixed, you should be able to rejoin that battle and delete it or continue it.  I did notice there are only 59 stories in that battle, not the 354 you stated.
