### ISSUE TITLE
What needs to be in the CSV file to import it properly?

### ISSUE THREAD

**Issue by Kurisutian** [StevenWeathers/thunderdome-planning-poker#425]
Hi there,

I just checked to import the CSV file rather than the XML for our purpose. However I am not sure what to actually export to the CSV file as both options, current and all fields both fail to be imported after on ticket. In both cases I chose a comma delimiter but it seemed not to work. So I might be missing something here which I am not aware of. Since I could not find anything in the documentation regarding the minimum requirements for a proper CSV file I might have more luck here. 😉 

Thanks and best regards!

**Comment by StevenWeathers** [comment]
The current example of the CSV as at

https://raw.githubusercontent.com/StevenWeathers/thunderdome-planning-poker/main/e2e/fixtures/csv-issues.csv

**Comment by StevenWeathers** [comment]
Example provided, please open new issue if further assistance is needed.
