### ISSUE TITLE
analytics disabled leads to errors while logging in/out

### ISSUE THREAD

**Issue by conrad784** [StevenWeathers/thunderdome-planning-poker#429]
Hi, since we upgraded in a self-hosted environment to v2.32.1 we see the behavior when logging in or out, that we are not redirected to the main page. The login/logout is actually executed, but main.js has the error
`Uncaught (in promise) ReferenceError: gtag is not defined` 
and therefore execution stops.

This is only the case if we have analytics.enabled set to false, and a workaround was to enable analytics while having an invalid gtag ID set.

I tried to have a look to create a PR, but I could only see that a lot of stuff was moved to svelte, but I did not understand how I would be able to fix this.

**Comment by StevenWeathers** [comment]
I will look into this asap.

**Comment by StevenWeathers** [comment]
Just tagged release `v2.32.3` which includes the fix for this bug.
