### ISSUE TITLE
Resolve environment variables in config?

### ISSUE THREAD

**Issue by jakauppila** [StevenWeathers/thunderdome-planning-poker#430]
With our container deployments, we push secrets via internally-standardized environment variables.

- `SECRETS_WEB_SERVICE_ACCOUNT_UPN`
- `SECRETS_WEB_SERVICE_ACCOUNT_PASSWORD`

Is there a way to push an environment variable reference within the yaml configurations for it to resolve the env var to use?

We're looking to map our service account username/pass env vars for `auth.ldap.bindname`/`auth.ldap.bindpass`.

**Comment by StevenWeathers** [comment]
Not that I'm aware of, you could pass the ENV values to the application instead of putting them in the yaml e.g.
```
AUTH_LDAP_BINDNAME=$SECRETS_WEB_SERVICE_ACCOUNT_UPN
AUTH_LDAP_BINDPASS=$SECRETS_WEB_SERVICE_ACCOUNT_PASSWORD
```

**Comment by jakauppila** [comment]
For simplicity, I added support for our internal secrets injection to be able to override the prefix/suffix to what the application is expecting.
