### ISSUE TITLE
[Poker] Ability to Import stories from Storyboard

### ISSUE THREAD

**Issue by jakauppila** [StevenWeathers/thunderdome-planning-poker#432]
Related to #431, as we build out our PI plan within the Storyboard it would be useful if you could import the stories created over there to a planning poker game for estimation. If you could export from the storyboard and import in the game, that would suffice, otherwise a direct import from a storyboard could be useful as well.

Or being able to associate a game to a storyboard so you could hop between either and estimate stories as they're created.

**Comment by StevenWeathers** [comment]
I love this idea since it utilizes the apps already existing feature and dataset, I can't promise this will be developed in time for your PI plan however if I can find time I will work on this.  Also will gladly accept any pull requests.

**Comment by pvi-github** [comment]
Hello,
I agree this would be brilliant !
