### ISSUE TITLE
[Poker] Ability to vote without explicitly defining stories

### ISSUE THREAD

**Issue by jakauppila** [StevenWeathers/thunderdome-planning-poker#438]
We have historically used planning poker apps on the side while sharing Jira, it would be useful to be able to vote without having to pop in a dummy story to vote on. (Maybe just another configuration option when creating a game?)

**Comment by jkamischke** [comment]
I would really like to see this feature. It could be useful for a quick estimation without the need of creating a user story.

**Comment by StevenWeathers** [comment]
Adding a single placeholder story to vote and revote is simple enough, adding non story voting is more complex therefor no plans to implement this myself.  I am open to any PRs that would.
