### ISSUE TITLE
[Auth] Add Google auth

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#443]
Allow users to sign up/login with Google account

Make use of https://github.com/coreos/go-oidc and `golang.org/x/oauth2`

**Comment by Jaz7Mutant** [comment]
It would be great if this feature will be configurable, so I could use my OIDC provider instead of Google in self-hosted scenario.

**Comment by scottux** [comment]
see #468

**Comment by StevenWeathers** [comment]
Closing in favor of OIDC provider support.
