### ISSUE TITLE
Add a toggle to switch themes

### ISSUE THREAD

**Issue by aslafy-z** [StevenWeathers/thunderdome-planning-poker#451]
Allow switching themes with a toggle in settings for eg.

On my linux distro, I had to add the `--force-dark-mode` flag to my Google Chrome browser to be able to see the dark theme, and I cannot go back to the light one without removing it.

**Comment by StevenWeathers** [comment]
This can be achieved with the style framework https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection in use now, not sure when I'll get to this request however willing to accept a PR as well.
