### ISSUE TITLE
Migrations without supeuser rights

### ISSUE THREAD

**Issue by Jaz7Mutant** [StevenWeathers/thunderdome-planning-poker#464]
I'm trying to self-host this app, but postgres user must have superuser rights to apply migrations. 
In one migration there is `CREATE EXTENSION IF NOT EXISTS  "uuid-ossp"` expression that requires superuser rights, but there is another migration with `DROP EXTENSION "uuid-ossp"`.
Also migrations will fail if there is no "pgcrypto" extension (I had to create it by myself). 
It would be great (and secure) if superuser rights won't be necessary to apply migrations

**Comment by StevenWeathers** [comment]
Unfortunately those can't be removed in the current version, however you're in luck as I'm working on version 3 which will be starting with fresh migration scripts that do not include the "uuid-ossp" extension at all.

**Comment by StevenWeathers** [comment]
[v3.0.0](https://github.com/StevenWeathers/thunderdome-planning-poker/releases/tag/v3.0.0) has been released, please give that a try and let me know if you run into any further issues.

**Comment by Jaz7Mutant** [comment]
Thank you! All migrations were successfully applied without superuser rights
