### ISSUE TITLE
Can't create retro. Serializer error

### ISSUE THREAD

**Issue by Jaz7Mutant** [StevenWeathers/thunderdome-planning-poker#474]
If you change "Max Group Votes (per User)" on retro creation page, then you won't be able to create retro.
```json: cannot unmarshal string into Go struct field retroCreateRequestBody.maxVotes of type int```
![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/48905747/37cd81ad-5e9f-4a31-bf0d-199f05f0ff61)

**Comment by StevenWeathers** [comment]
Thanks I think I know the cause and will fix this asap.

**Comment by StevenWeathers** [comment]
Fix pushed, thank you for reporting!
