### ISSUE TITLE
Can't start with Compose

### ISSUE THREAD

**Issue by snlucas** [StevenWeathers/thunderdome-planning-poker#478]
Hi. I was trying to configure the project following the developing.md guide.
I tried to use this command:
`docker-compose up --build`

and it returned this error:
`
failed to solve: failed to compute cache key: failed to calculate checksum of ref c8e4b0b9-1f79-41c8-bc3c-1482dbe4d5d3::h8wuc5j58ue62inbahqid9itt: "/db": not found
`

![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/30248076/d65447bd-1cf8-4031-be1a-5988230a2f4a)

I found this [issue](https://github.com/StevenWeathers/thunderdome-planning-poker/issues/348#issue-1303274220), and tried to run this command:
`docker compose up db`

This happens:
![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/30248076/ca646297-5fbc-47a8-88c3-70b3e2919838)

So I tried to run this one in another terminal:
`docker compose up thunderdome`

and got this error:
![image](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/30248076/6aa4ca25-0d79-4f5a-a68c-0ffaa743256d)

Any tip on this?

**Comment by StevenWeathers** [comment]
Just committed a fix for the dockerfile, honestly I never use docker for local development so it was a miss since changing the directory structure.  Try again and let me know if you experience further issues.

**Comment by snlucas** [comment]
Hi, Steven.
It worked pretty well!
Thank you very much, man.
