### ISSUE TITLE
(Bug?) Plan deletion stopped working (Saas)

### ISSUE THREAD

**Issue by shoesack** [StevenWeathers/thunderdome-planning-poker#492]
Hey, seems the deletion of plans inside a battle stopped working (SaaS).

Tested this behaviour in Chrome, Firefox and Safari. 

Delete button stays without function. No console errors thrown.

Can someone double check in the SaaS version?

**Comment by StevenWeathers** [comment]
I'm unable to replicate this issue, can you try again?

**Comment by shoesack** [comment]
Still facing the same issue. Wondering because its working in other battles as expected. 

Only one specific battle is facing this issue. I stil can edit existing or add plans manually or via Jira XML. But deletion...nah nah ^^ 

Absolutely no clue what happened! I even wen thru all plans and removed special characters in the hope this was the issue.

**Comment by StevenWeathers** [comment]
I'm seeing the error in logs, not sure how it's an issue but if you could send me the battle ID via email I can try and fix it.
