### ISSUE TITLE
Subscription does not work

### ISSUE THREAD

**Issue by lino** [StevenWeathers/thunderdome-planning-poker#493]
After subscribing to the pro tier, the subscription is not registered in the backend. Payment went through. No big deal, but I thought you'd like to know.

**Comment by StevenWeathers** [comment]
I'll definitely take a look, how are you determining its not registering in the backend?

**Comment by StevenWeathers** [comment]
According to the subscription processor your payment did not complete successfully.  If you'd like I can send further details to your email.

**Comment by lino** [comment]
Wicked. You'd think payment would be solved by now. I'll try again.
