### ISSUE TITLE
[Login] Hide guest registration box if feature is disabled and improve registration/login redirect logic

### ISSUE THREAD

**Issue by budokaiman** [StevenWeathers/thunderdome-planning-poker#494]
There are two issues with the login/registration flow that I notice currently:
1. If guest registration is disabled, the register as guest box still shows up and allows users to attempt to register as a guest. When a user tries to register as a guest, an error occurs, without any information that the feature is disabled.
2. When navigating to a battle, retro, or storyboard, if guest registration is disabled, the default re-route is to the registration page if guest or normal registration is enabled. This can be confusing to users as they will try to re-register if they already have an account. It would make more sense to default to the login page if only guest registration is not enabled as there won't be any guest registrations, just the one time registration and subsequently everything will be logins.

I have some changes that address both of these, which I'll open a PR for.

**Comment by scottux** [comment]
This issue can be closed now that #495 has been merged.
