### ISSUE TITLE
[Retro] Event conflicts in grouping phase can wipe group names

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#518]
It's been reported that sometimes when multiple users are manipulating groups the group names can get wiped out.

One possible solution is to separate grouping and naming groups into unique phases.

**Comment by scottux** [comment]
Seems like an opportunity to make the e2e tests more active if that makes sense. I am not sure how else to test these situations. 

While testing the grouping, have some simulated backend chatter, and have the group moved around and keep checking the state of it?

**Comment by StevenWeathers** [comment]
My experience with e2e tests would say that'll be difficult to simulate, mainly because I'm not certain if it's a network timing issue.  I do see a possible simple fix in how the grouping and naming events are handled on the UI.  Currently they update all the groups, even though only one was changed.  It would be best to make them more targeted which should fix the issue I think.

**Comment by StevenWeathers** [comment]
PR #531 hopefully resolves this issue by reducing the impacts of socket events on grouping phase and also no longer sorts the groups during grouping phase which would cause a jarring experience.

**Comment by StevenWeathers** [comment]
Marking this done, if it occurs again will reopen or open new ticket.
