### ISSUE TITLE
[Retro] Add configurable timer to brainstorm phase

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#525]
Most teams likely schedule a timeslot for Retro and having the ability to timebox brainstorming phase would be helpful.

**Comment by scottux** [comment]
ok, so

## models

retro creation would get a _timebox_ option, which would be a selectable number of minutes between _1 and 10_.

phases would have a _startTime_ timestamp attribute

## logic

if phase's parent _retro timebox minutes_ > 0
  on phase start
    set the _startTime_ timestamp attribute
    countdown from _startTime_ for _retro timebox minutes_

if _now_ > (_startTime_ + _retro timebox minutes_)
  set phase done

## optionally

we could also add a timerFinal boolean option to control the logic for setting phase done or not.
