### ISSUE TITLE
Add Support page with contact form

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#528]
To allow end users to contact the administrator directly with support questions add a support page linked in footer of application.

Page should include link to Github Repo Issues section, as well as a contact form that submits to db and sends email to the administrator(s).

**Comment by scottux** [comment]
What fields should be in the form?

**Comment by StevenWeathers** [comment]
I have an active PR with the starting point for this issue, has the fields planned out already.

**Comment by StevenWeathers** [comment]
Closing as a support page is live however not doing support for yet.
