### ISSUE TITLE
[Feature Request]: Add intro to retro's page

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#559]
### Description

It would be nice to intro users to what a sprint retrospective is and why this Thunderdome feature aids remote teams in this agile practice.

### Describe the solution you'd like

It could be a small banner that leads to another more in depth guide from a "Learn more" call to action.

### Describe alternatives you've considered

Relying on landing page to pitch the feature.

**Comment by scottux** [comment]
@etuncay has a package that might work.

**Comment by scottux** [comment]
https://github.com/etuncay/svelte-intro.js looks like a decent option for wrapping introjs in Svelte. I would give it a shot.

**Comment by StevenWeathers** [comment]
Another option might be https://shepherdjs.dev/ which is actually written in Svelte for its core.

**Comment by StevenWeathers** [comment]
Quick test of shepherdjs seems really easy to set it up and go.

<img width="682" alt="image" src="https://github.com/StevenWeathers/thunderdome-planning-poker/assets/846933/ff05b643-31d3-47cb-a651-5f8fdf1b3b16">

**Comment by StevenWeathers** [comment]
For now I've added a description on what a retro is to the bottom of the retro's page, a guided tour seems too invasive and requires great content to drive it.
