### ISSUE TITLE
[Feature Request]: allow leaders to nudge other leaders

### ISSUE THREAD

**Issue by gwimmel** [StevenWeathers/thunderdome-planning-poker#569]
### Description

If there are multiple leaders in a battle (e.g. taking turns or replacing each other), all leaders can vote, but a leader currently cannot nudge another leader for a vote. Is this intentional?

### Describe the solution you'd like

Allow leaders to nudge other leaders (maybe configurable?)

**Comment by StevenWeathers** [comment]
Nudge was intended to be used by the active facilitator (leader), I didn't think about nudging other facilitator's though the feature would work just fine if the button was there (nothing in the backend prevents it).

**Comment by gwimmel** [comment]
Yes, looking at the code I think it should be easy to adapt such that this is possible. I can try and provide a PR.
