### ISSUE TITLE
[Feature Request]: Adding an email to a team should add it too in parent Department and Organization automatically

### ISSUE THREAD

**Issue by pvi-github** [StevenWeathers/thunderdome-planning-poker#575]
### Description

Currently in Thunderdome, to add a new user to a team it needs to be known of the parent entity.

The result is that to add a new user we need first to add him/her to the Organization. Then wait for him/her to validate the account. Then add him/her to the department. Then add him/her to the team.

This is painful.

### Describe the solution you'd like

I suggest that :
1) A new role "ACCESS" allowing only to get through structure is added. This role, aside MEMBER and ADMIN will  allow people to "get in" but only that and not get deeper in departments or teams.

2) Wherever in the company structure an email is added as member or admin:

__2a) if the user does not exist 
____2a1) the user is created in the database with a "waiting validation" flag on it.
____2a2) A mail is sent to the user for valiadtion
____2a3)  The role MEMBER or ADMIN is set up in the database for the Team/Department/Company
____2a4) If it's not a company, in the parents (dept, company) an "ACCESS" role is granted to the user so that he/she sees it and can enter it but only that.
____2a5) If it's not a team, in the children the same role as set up (MEBER or ADMIN) is granted recursively.

__2b) if the user does exist 
____2b1)  The role MEMBER or ADMIN is set up in the database for the Team/Department/Company
____2b2) If it's not a company, in the parents (dept, company) an "ACCESS" role is granted to the user so that he/she sees it and can enter it but only that.
____2b3) If it's not a team, in the children the same role as set up (MEBER or ADMIN) is granted recursively.

3) After a certain time if the user did not validate his account the account is deleted and all the roles granted whether ACCESS / MEMBER / ADMIN

This way admins will only have to enter the mail once to the correct Team to set up things.
And nice bonus :  by default people of various teams will not be able to see what other teams do which is good for security.

What do you think ?

**Comment by StevenWeathers** [comment]
I'm open to this enhancement, not sure how soon I will get to it though.

**Comment by StevenWeathers** [comment]
Since I just merged a change to inviting users to teams I will go ahead and take this on next.
