### ISSUE TITLE
[Feature Request]: RETRO. Unable to regain being Facilitator once removed

### ISSUE THREAD

**Issue by davidhaase** [StevenWeathers/thunderdome-planning-poker#582]
### Description

**Description**
During a well-formed Retro, if the Facilitator clicks to not be a facilitator, it's impossible to regain being one -- if the Fac.Code was never created.

**Steps to Reproduce**
1. Create a Retro, but do NOT create a Fac.Code 
2. Joint the Retro
3. Click to not become a facilitator
4. Try to advance the board - -as expected, you can't because you're no longer a Facilitator
5. Now click "Become Facilitator"
6. Observe the Code Entry pop-up --

**Expected**
If the Fac. Code was optional (i.e., empty), having a pop-up is unexpected. I would have thought you could just become Facilitator

**Observed**
The Pop-Up to enter the Fac. Code appears unexpectedly.  Since it was "empty" and never declared, it's not clear what to do. 
 _But more importantly,_ it's now impossible to become a facilitator again, and the Retro can not advance -- the retro is wasted and all ideas that were brainstormed are lost. 

### Describe the solution you'd like

No Pop-Up
If the fac.code was never declared, the pop-up should not appear and whoever reqeusts to be facilitator simply becomes one.

### Describe alternatives you've considered

Or, an empty field should work
If the fac.code was never decalrd and the pop-up still appears, then simply clicking "SAVE" (leaving the input box empty) should allow the user to become facilitator.

**Comment by davidhaase** [comment]
![Screenshot 2024-07-10 at 10 24 42 AM](https://github.com/StevenWeathers/thunderdome-planning-poker/assets/28824622/8b0ce687-cd0e-469b-beb7-a8a3934ca7bb)

**Comment by StevenWeathers** [comment]
I think another solution is to not allow the only/last facilitator to remove themselves as a facilitator.
