### ISSUE TITLE
[Feature Request]: Custom card values

### ISSUE THREAD

**Issue by 13hannes11** [StevenWeathers/thunderdome-planning-poker#587]
### Description

My team uses a different way to estimate (in hours) and thus we are missing that more different values can be used. Also we apply a factor to estimations so we are missing the ability to set an arbitrary value for the final result.

### Describe the solution you'd like

A great feature would be to be able to get any numeric values on the cards that I want or to have an additional chose your own card where people can enter a custom value.

### Describe alternatives you've considered

There is no alternative besides not using this tool.

**Comment by apemother** [comment]
+1

**Comment by StevenWeathers** [comment]
You can set custom values for cards if you self-host, as far as selecting a final value that isn't on the cards that would be a new enhancement as well.

**Comment by StevenWeathers** [comment]
You can now select from multiple point scale templates and set an arbitrary final vote value (with a max character length of 8).  Working on the next enhancement now to allow creating custom estimation scales at the Organization and Team levels.
