### ISSUE TITLE
[Bug]: Wrong url to /admin/games

### ISSUE THREAD

**Issue by kaaac** [StevenWeathers/thunderdome-planning-poker#589]
### Description

In the Admin space, the tab for managing Games leads to the url "<baseurl>/admin/battles".
The same applies to the links to individual Games from the admin panel

### Describe the solution you'd like

fix url of button to "/admin/games"

### Describe alternatives you've considered

Manually entering the address with /admin/games works correctly.

**Comment by StevenWeathers** [comment]
Fixed in Release `v4.0.1`
