### ISSUE TITLE
External Authentication

### ISSUE THREAD

**Issue by cfraenkel** [StevenWeathers/thunderdome-planning-poker#60]
I'd like to authenticate my users using openid / oauth2 proxy (https://pusher.github.io/oauth2_proxy/)  with single sign on.
This works well so far with the exception that users still have to register in the app again. It would be great if I could configure thunderdome so that it accepts proxy authentication using a configurable header (in my case,  `x-auth-request-preferred-username` or `x-auth-request-email`) passed in by my nginx ingress.

**Comment by StevenWeathers** [comment]
I'm open to ideas, however the current authentication was designed to be self standing.  Integrating any Single Sign On such as openid/oauth2 isn't something currently planned for.  I can think about possible solutions but don't know when I will get to that.

**Comment by StevenWeathers** [comment]
Closing this with no plans to implement external authentication at this time.
