### ISSUE TITLE
[Bug]: config allowedPointValues has no efect

### ISSUE THREAD

**Issue by andreipop8x8** [StevenWeathers/thunderdome-planning-poker#604]
### What happened?

If we set allowedPointValues in /etc/thunderdome/config.yaml has no effect in UI

`config:
  allowedPointValues: "0, 1, 2, 3, 5, 8, 13, 20, 21, 34, 40, 55, 100, ?"

  defaultPointValues: "0, 1, 2, 3, 5, 8 , 13, ?"`

![image](https://github.com/user-attachments/assets/8887c15f-1f25-4115-9eb2-6562fda74b6c)

### Self Hosted?

Yes

### Version

v4.6.0

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
I have verified the environment variable works for this config item, will have to debug to see why the yaml value isn't parsing.

**Comment by StevenWeathers** [comment]
With the latest enhancement this config item will be going away in the next major version, you can omit it and just manage point scales in the database now (Admin and Team/Org UIs coming soon for custom scale management).

**Comment by andreipop8x8** [comment]
Hello @StevenWeathers 
Can you please tell me what table(s) I have to edit?
Thank you.

**Comment by StevenWeathers** [comment]
> Hello @StevenWeathers Can you please tell me what table(s) I have to edit? Thank you.

the `estimation_scales` table, you'll see a few examples already available as the app ships with some default standard scales and a custom thunderdome one.
