### ISSUE TITLE
Add/Edit Plan Modal Too Small

### ISSUE THREAD

**Issue by TzolkinB** [StevenWeathers/thunderdome-planning-poker#61]
When I split my laptop view in half, it's roughly 840px which is the screenshot. The modal is a little narrow to type in. The modal also appears small on ipadPro, also attached. 

<img width="1094" alt="Screen Shot 2020-03-31 at 10 08 51 AM" src="https://user-images.githubusercontent.com/10334517/78046084-b7fcf480-7344-11ea-854f-b83f8dc21672.png">

<img width="499" alt="Screen Shot 2020-03-31 at 11 44 43 AM" src="https://user-images.githubusercontent.com/10334517/78046476-3194e280-7345-11ea-8e19-9160be4d84e2.png">

**Comment by StevenWeathers** [comment]
Thanks I will fix this asap.

**Comment by TzolkinB** [comment]
Looks great. Thank you! 👍
