### ISSUE TITLE
[Bug]: Difficulties joining game

### ISSUE THREAD

**Issue by quangdng** [StevenWeathers/thunderdome-planning-poker#613]
### Contact Details

justin.nguyen@persuit.com

### What happened?

<img width="938" alt="Screenshot 2024-09-12 at 1 10 22 PM" src="https://github.com/user-attachments/assets/d375c688-1e17-42af-98bc-4a62fe880416">

Hi Steven,

We see this happen a lot lately, reported by multiple team members when joining their games.

Can you please have a look?

Kind regards,
Justin

### Self Hosted?

No

### Version

Latest

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
Can you have those users check their web browser console and see if there are any errors?
Network tab as well if possible?

I'll check the server logs, just not sure how easy this will be to notice.

**Comment by quangdng** [comment]
<img width="938" alt="Screenshot 2024-09-12 at 1 45 39 PM" src="https://github.com/user-attachments/assets/5dd2ab72-77bc-4c6d-bbab-856b1e06d9bd">

Thanks Steven. This is the log, it just kicked me out as I am doing the session now.

**Comment by StevenWeathers** [comment]
Yea I restarted the app should be faster now since I think I've found a potential root cause on my infrastructure, I've changed some things let me know if the issue persists.

**Comment by quangdng** [comment]
Thanks @StevenWeathers. Appreciate it! I will close the issue for now.
