### ISSUE TITLE
[Feature Request]: Retro - Grouping phase : As a Facilitator, I would like to easily see the category of the feedback we are talking about

### ISSUE THREAD

**Issue by sneeze** [StevenWeathers/thunderdome-planning-poker#618]
### Description

If the feedback is about Start, Stop, Continue. Seeing only the color doesn't help me a lot about which is the green category. I have to go back and forth in the screen before to know which category we are talking about.

### Describe the solution you'd like

The feedbacks could stay in the column they used to be in the screen before. So in the screen Grouping, we see Start column, Stop column, Continue columnn, with each of the feedback written under each of the columns

### Describe alternatives you've considered

a hover over the color to tell us which category. But the feedbacks need to be ordered by column name so the Start feedbacks are not everywhere

**Comment by StevenWeathers** [comment]
Since groupings are not restrictive of column type I think there are considerations for this, like perhaps having a color legend on the page or showing a tag/label on the item that signifies which type it is.
