### ISSUE TITLE
[Feature Request]: Retro: As a Facilitator, I would like to have a place where I can see all the past Retro Action Items. 

### ISSUE THREAD

**Issue by sneeze** [StevenWeathers/thunderdome-planning-poker#619]
### Description

 I would like to have a place where I can see all the past Retro Action Items so at the beginning of the retro i can focus on what is not finished and see the status of them with the team before brainstorming on something new.

### Describe the solution you'd like

A page section where all the retro action items are visible. We can review them Live and decide if we keep them or if it is done and we can close it.

**Comment by StevenWeathers** [comment]
Great idea!  I think for this one I would envision a button like "Review Open Action Items" that pulls the list of open action items for the team associated to the retro.  Of course if a retro is not associated to a team this wouldn't be simple as tracking across retros becomes a bit more variable if they're spread across users.
