### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by eXtrem0us** [StevenWeathers/thunderdome-planning-poker#62]
Hi  Steve,

We're using your project for our scrum planning in our office and it is great in such covid19 situation and remote working.

I think it would be a good idea to have the ability to integrate with LDAP/Active Directory.
So that the corporate users can log in with their predefined credentials and don't have to register with their emails… 

Thank You.

**Comment by StevenWeathers** [comment]
Can't say for certain I'll get to this feature request, however feel free to fork and add as you need.

From my preliminary research it looks like a decent golang library exists for LDAP.
https://github.com/go-ldap/ldap

**Comment by StevenWeathers** [comment]
I do not plan on implementing this feature at this time, however any PRs that add this will be considered so long as the solution works well with the current authentication model without adding too much complexity or risk.

**Comment by eivindt** [comment]
I have a working implementation, I need to update it to the latest master and issue a pull request one of these days.

**Comment by StevenWeathers** [comment]
@eivindt that would be awesome, I know others would appreciate it.

**Comment by StevenWeathers** [comment]
@eXtrem0us this functionality has been implemented by @eivindt and merged to master.

**Comment by eXtrem0us** [comment]
Thank you guys! @eivindt @StevenWeathers
