### ISSUE TITLE
[Poker] Median calculated instead of average

### ISSUE THREAD

**Issue by SoanAnna** [StevenWeathers/thunderdome-planning-poker#633]
### Contact Details

soan.anna@seznam.cz

### What happened?

Hi, 
my team has been using Thunderdome Poker for couple years and we were used to get the result of game as average of the votes.
But now, even when we set up a new game and select desired rounding option, average is not calculated. The result board always shows median.
Is this a bug or intentional change? Can there be option to choose if users want to see average or median?
Thank you.
Anna

### Self Hosted?

Yes

### Version

4.16.5

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
The results change was to support non number results such as tshirt sizing, the "median" is calculated to more accurately portray the average vote that is actually one of the cards.  I'll consider adding the average that doesn't match the cards for use-cases where the cards are strictly numbers.
