### ISSUE TITLE
[Feature Request]: Poker: Support for configuring default rounding method

### ISSUE THREAD

**Issue by tberreis** [StevenWeathers/thunderdome-planning-poker#634]
### Description

`Point Average Rounding` can be Ceil, Round or Floor where Ceil is the default when creating new games and I didn't find a way to change this behaviour.
For some teams a different method is much more suitable but it shouldn't be required to change it every time when creating a game.

### Describe the solution you'd like

The default method could be configurable either in the database or in the app config.

**Comment by StevenWeathers** [comment]
This will cover the basic app configuration of the default rounding method, further tickets will cover the premium features for organizations/teams to define custom defaults.

**Comment by tberreis** [comment]
> This will cover the basic app configuration of the default rounding method, further tickets will cover the premium features for organizations/teams to define custom defaults.

Thanks a lot for this fast implementation!
