### ISSUE TITLE
[Feature Request]: Modification of poker stories via API

### ISSUE THREAD

**Issue by heinezen** [StevenWeathers/thunderdome-planning-poker#645]
### Description

Change existing poker stories in a game via the API would be a really nice addition to the already possible creation and deletion of stories. In my case, the title and priority of poker stories can sometimes change before a game is completed by me and my co-workers. When this happens, I would like to update the affected story with new information.

### Describe the solution you'd like

Supporting `PUT` (and maybe also `PATCH`) for the `/battles/{battleId}/plans/{planId}` path in the API would probably solve this feature request. `PUT` would overwrite the current poker story data, while `PATCH` would be a bit simpler for partial updates.

### Describe alternatives you've considered

Currently, the only workaround I can use is to delete the story and recreate it using the same data. However, this does not preserve all metadata of the plan I believe, so it is not feasible in all situations.

**Comment by StevenWeathers** [comment]
Adding a `PUT` endpoint for story would be trivial given thats the underlying design of the websocket event handler, `PATCH` would be more complex.

**Comment by heinezen** [comment]
I would already be happy with `PUT` :) Later I can make a separate issue for `PATCH` if there's demand.
