### ISSUE TITLE
[Bug]: "X out of Y stories pointed" in poker games overview shows incorrect values

### ISSUE THREAD

**Issue by heinezen** [StevenWeathers/thunderdome-planning-poker#646]
### What happened?

There is a funny bug in the "My Games" overview that lets the interface display a wrong number of points. For example, the "My Games" overview will say "10 out of 20 stories pointed", even though there are only 5 out of 10 poker stories pointed.

I tried to investigate this a little bit since the numbers were not consistently calculated wrong, but the wrong numbers were always double or triple of the correct number of stories. I'm pretty sure that the issue is that both numbers are **erroneously multiplied by the number of leaders in the game**. For example, if there are actually 5 out of 10 stories rated, the UI will show "10 out of 20" if there are 2 leaders, "15 out of 30" if there are 3 leaders, and so on.

### How To Reproduce

1. Create a new poker game
2. Add a few stories to the game and vote on them, e.g. 2 out of 4 stories total. The overview in My Games should say "2 out of 4 stories pointed".
3. Add a new user to the game and make them leader. The overview in My Games should say "4 out of 8 stories pointed".

### Self Hosted?

No

### Version

Latest

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
I think the root cause of this bug is something I've seen before, I will take a look at this one this week.
