### ISSUE TITLE
[Bug]: LDAP Auto-Recruit Not Working

### ISSUE THREAD

**Issue by kasualkeef** [StevenWeathers/thunderdome-planning-poker#651]
### What happened?

I have Thunderdome deployed on a 1.29.x k8s cluster using the latest images. Everything seems to be working except for the LDAP auto-recruit. I can see the app connect to the DB and successfully build the tables/schema in the logs. The web front end is also working fine. However, when I try to log in with an LDAP user I get the log entry below and the web UI seems like it's about to log in but then bounces me back out (with 401s in the browser console).

{"level":"error","ts":1732737258.5433009,"caller":"http/util.go:221","msg":"User does not exist in database, auto-recruit","version":"","useremail":"REDACTED","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/internal/http.(*Service).authAndCreateUserLdap\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/util.go:221\ngithub.com/StevenWeathers/thunderdome-planning-poker/internal/http.New.(*Service).handleLdapLogin.func3\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/auth.go:141\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.55.0/mux.go:169\ngithub.com/unrolled/secure.(*Secure).Handler-fm.(*Secure).Handler.func1\n\t/go/pkg/mod/github.com/unrolled/secure@v1.16.0/secure.go:198\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/StevenWeathers/thunderdome-planning-poker/internal/http.(*Service).panicRecovery-fm.(*Service).panicRecovery.func1\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/middleware.go:25\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3210\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2092"}

Thanks!

### Self Hosted?

Yes

### Version

Latest

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Relevant log output

```shell
{"level":"error","ts":1732737258.5433009,"caller":"http/util.go:221","msg":"User does not exist in database, auto-recruit","version":"","useremail":"REDACTED","stacktrace":"github.com/StevenWeathers/thunderdome-planning-poker/internal/http.(*Service).authAndCreateUserLdap\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/util.go:221\ngithub.com/StevenWeathers/thunderdome-planning-poker/internal/http.New.(*Service).handleLdapLogin.func3\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/auth.go:141\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngo.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux.traceware.ServeHTTP\n\t/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux@v0.55.0/mux.go:169\ngithub.com/unrolled/secure.(*Secure).Handler-fm.(*Secure).Handler.func1\n\t/go/pkg/mod/github.com/unrolled/secure@v1.16.0/secure.go:198\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/StevenWeathers/thunderdome-planning-poker/internal/http.(*Service).panicRecovery-fm.(*Service).panicRecovery.func1\n\t/go/src/github.com/stevenweathers/thunderdome-planning-poker/internal/http/middleware.go:25\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3210\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2092"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
That log means it should create the user in the database as per the following conditions that occur after that log line.  Do you see one of the following logs right after that log?

```go
authedUser, verifyID, err = s.UserDataSvc.CreateUserRegistered(ctx, usercn, useremail, "", "")
if err != nil {
			s.Logger.Ctx(ctx).Error("Failed auto-creating new user", zap.Error(err))
			return authedUser, sessionID, err
		}
		err = s.AuthDataSvc.VerifyUserAccount(ctx, verifyID)
		if err != nil {
			s.Logger.Ctx(ctx).Error("Failed verifying new user", zap.Error(err))
			return authedUser, sessionID, err
		}
		sessionID, err = s.AuthDataSvc.CreateSession(ctx, authedUser.ID, true)
		if err != nil {
			s.Logger.Ctx(ctx).Error("Failed creating user session", zap.Error(err))
			return authedUser, sessionID, err
		}
		```

**Comment by kasualkeef** [comment]
Thanks for the quick response.

No, nothing is logged after that line. I don't see anything in the DB logs either.

**Comment by StevenWeathers** [comment]
I would expect an error log after the fact unless its happening at the browser side, I don't have an LDAP setup to try and debug this flow as its mostly a contribution from others.  If you could debug on your end I'd be happy to help guide a resolution.

**Comment by kasualkeef** [comment]
It looks like this is actually caused by the NGINX proxy in front of the app. I'm running the nginx-ingress (F5) ingress controller in my k8s cluster. If I do a simple kubectl port forward, Thunderdome creates the user and logs in without issue. However, when behind the proxy, I get a 401 from the /api/ resources after clicking login.

The NGINX controller config looks like this:
        
    location / {
                set $service "thunderdome";
                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_cache_bypass $http_upgrade;

                proxy_connect_timeout 60s;
                proxy_read_timeout 60s;
                proxy_send_timeout 60s;
                client_max_body_size 1m;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_buffering off;
                proxy_pass http://thunderdome-poker-thunderdome-app-ingress-thunderdome.domain.com-thunderdome-8080;
        } 

I have a bunch of apps successfully using this ingress controller with similar configurations. If there something in the NGINX config I might be missing for Thundedrdome?

**Comment by kasualkeef** [comment]
I'm an idiot.

I'm running NGINX ingress in front of the app and I forgot to set the [`http.domain` variable ](https://github.com/StevenWeathers/thunderdome-planning-poker/blob/main/docs/CONFIGURATION.md#required-configuration-items)

I set the correct HTTP domain, and I no longer get bounced out after login. Auto-recruit was working fine; it was rejecting my session cookie on login after the user creation.
