### ISSUE TITLE
[Bug]: No good readability with too small votes

### ISSUE THREAD

**Issue by DocBrown101** [StevenWeathers/thunderdome-planning-poker#654]
### What happened?

The numbers overlap and are therefore difficult to read:
![image](https://github.com/user-attachments/assets/c5d83eb9-f29a-4f0b-bab4-2255f4d0d389)

### Self Hosted?

Yes

### Version

Latest

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by StevenWeathers** [comment]
<img width="151" alt="image" src="https://github.com/user-attachments/assets/10ba5527-342a-4b24-a5cf-c845d0660954" />

Fixed in `v4.18.7` release

**Comment by DocBrown101** [comment]
Thank you very much, that was quick!
