### ISSUE TITLE
SCRIPT1028: Expected identifier, string or number in Microsoft Edge

### ISSUE THREAD

**Issue by cfraenkel** [StevenWeathers/thunderdome-planning-poker#70]
When I try to access https://thunderdome.dev/ using microsoft edge 

Version:
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

I'm getting the following error:
SCRIPT1028: SCRIPT1028: Expected identifier, string or number 
bundle.8f56f56189fa8d8e572967ca00edfefc.js (1,117643)
The displayed page is blank.

When I jump to the error the following js is displayed:
![image](https://user-images.githubusercontent.com/20723556/82306600-8c4ed000-99bf-11ea-9e09-1a406e53a88a.png)

**Comment by StevenWeathers** [comment]
I don't have Edge but I will do my best to see what might be the issue and try to resolve it.

**Comment by cfraenkel** [comment]
I can try and provide additional information (as long as I know whats needed) or do some testing next week.

**Comment by StevenWeathers** [comment]
I think I see some code that may be the issue for Edge.

**Comment by cfraenkel** [comment]
if it helps narrowing it down, I remember edge still working with https://github.com/StevenWeathers/thunderdome-planning-poker/commit/df6313e1b6e9a60e802ede7dfebec629de384d60

**Comment by StevenWeathers** [comment]
> if it helps narrowing it down, I remember edge still working with [df6313e](https://github.com/StevenWeathers/thunderdome-planning-poker/commit/df6313e1b6e9a60e802ede7dfebec629de384d60)

Yup I've found the culprit its a rest parameters spread, I will have to tweak the function but it won't be that big of a deal.
