### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by thiemok** [StevenWeathers/thunderdome-planning-poker#77]
*Summary*
The login seems to be currently not working on the latest docker image.

*Steps to reproduce*
* Run current latest image
* Sign up with new account
* Log out
* Try to login

* Expected behaviour*
* Login works

I believe this is due to a recent change in the linked function
https://github.com/StevenWeathers/thunderdome-planning-poker/blob/a4dcac166b13c5996acf6d9bf88a4955629b522c/pkg/database/warriors.go#L36

It seems like avatar and password are being read in reverse from the db, thus supplying the wrong value to the password check

**Comment by StevenWeathers** [comment]
Wow great find!, fixing asap.
