### ISSUE TITLE
Add configurable option to change verbiage in UI to be more work friendly

### ISSUE THREAD

**Issue by StevenWeathers** [StevenWeathers/thunderdome-planning-poker#89]
While the theme is fun, I can see how some companies would rather not have the verbs be centered around Battling.

Add an option like "friendly_ui_verbs" which is then used to determine the set of vocabs used in the UI.
This would require abstracting the verbs as to avoid additional conditions everywhere.  The verbs could be passed from backend or just set globally on UI load based on the app config switch (Default false).

Verb replacements

Battle = Session?
Warrior = User?
Plan = Story

**Comment by vasileknik76** [comment]
Also you can think about localization files. For example, i'm from Russia and i'd like to have Russian interface.

**Comment by StevenWeathers** [comment]
@vasileknik76 Feel free to create new issues, I'm open to ideas and thats the best way to share them so others may contribute as well.  That is a great idea by the way.
