### ISSUE TITLE
Version in footer

### ISSUE THREAD

**Issue by tnonnenm** [StevenWeathers/thunderdome-planning-poker#98]
Hi, I'm lost in the release candidates :-)

Is it possible to add the Git-Tag as version to the footer during (docker-compose) build?

![version-example](https://user-images.githubusercontent.com/43718273/95983278-a3380800-0e21-11eb-9fca-4fb333d8ad8a.png)

The link could point to the tag in GitHub, for my example this would be https://github.com/StevenWeathers/thunderdome-planning-poker/releases/tag/v1.0.0-rc.26.

I searched the internet to see if I can add such a feature but was not successful ... maybe you have an idea?

**Comment by StevenWeathers** [comment]
I've been considering something like this, I will do some research to determine possible ways to achieve it while supporting the build process for both single binaries and docker images.
